---
title: "building native forest law impact dataframes"
#author: "Albert Garcia"
output:
  pdf_document:
    number_sections: yes
    toc: no
fontsize: 11pt    
documentclass: article
geometry: margin=1in
header-includes: 
  \usepackage{sectsty}
  \usepackage{enumitem}
  \usepackage{comment}
  \usepackage{multirow,array}
  \usepackage{makecell}
  \usepackage{dcolumn}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(out.height='300px', dpi=200)

### loads tidyverse packages, defines helper functions
library(latex2exp)
library(tidyverse)
library(ggplot2)
library(readxl)
library(sf)
library(stringi)
library(data.table)
library(kableExtra)
library(stringdist)
library(GADMTools)
library(rnaturalearth)
library(lwgeom)
library(units)
#library(reshape2)

library(did)
library(AER)
library(dynlm)
library(plm)
library(stargazer)
library(Metrics)
library(DataCombine)
library(Hmisc)

```


```{r geoms, echo = FALSE, message = FALSE, warning = FALSE, include = FALSE, eval = TRUE}

rolarea_df <- st_as_sf(readRDS("rolarea_df.rds"))%>%
  st_sf(sf_column_name = "geometry", crs = "+proj=longlat +datum=WGS84")

```


``` {r awarded NDVI, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE, eval = TRUE}


#setting working directory

setwd("C:/Users/garci/Dropbox/chile_reforestation/data/property_ndvi/new_CIREN_ndvi")

#upload and bind csvs together
awarded_ndvi <- 
  list.files(pattern = "*.csv") %>% 
  map_df(~read_csv(.)) %>%
  as.data.frame() %>% #turn into dataframe
  rename(prop_ID = Code)
```

```{r}
awarded_ndvi2 <- read.csv("C:/Users/garci/Desktop/chile_data/rol_area_ndvi.csv")%>%
  rename(ndvi2 = mean,
         Year = year,
         prop_ID = 3)

awarded_ndvi2$prop_ID <- as.integer(awarded_ndvi2$prop_ID)
#match NDVIs with dataset
df_awarded <- awarded_ndvi %>%
  inner_join(rolarea_df, by = "prop_ID") %>%
  inner_join(awarded_ndvi2, by = c("prop_ID", "Year"))
  
first_awarded <- df_awarded %>%
  filter(first.treat == rptpro_ano) %>%
  bind_rows(readRDS("rejected_panel_2.rds"))%>%
  bind_rows(readRDS("rejected_panel.rds"))%>%
  distinct(Year, prop_ID, .keep_all = TRUE)

rejected_plotttters <- later_awarded %>%
  inner_join(awarded_ndvi, by = c("prop_ID"))%>%
  bind_rows(readRDS("rejected_panel_2.rds"))%>%
  bind_rows(readRDS("rejected_panel.rds"))%>%
  mutate(ndvi = ifelse(Year > first.treat, NA, NDVI))
  


```

``` {r awarded panel, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE, eval = TRUE}
first_awarded <- first_awarded %>%
  mutate(early.enroller = ifelse(first.treat <= 2012, 1, 0))

otros_trendplot_df <- first_awarded %>%
  filter(first.treat ==2009|first.treat ==2019|first.treat ==2010|first.treat ==2018
         )%>%
  #filter(#rptpro_tipo_concurso == "Otros Interesados" #&
          # Year <=2012
   #      )%>%
  group_by(first.treat, Year, early.enroller
           )%>%
  summarise(ndvi = mean(NDVI, na.rm = TRUE))%>%
  rename(award_year = first.treat)

otros_trendplot_df$award_year <- as.factor(otros_trendplot_df$award_year)

otros_trendplot_df$early_enroller <- as.factor(otros_trendplot_df$early.enroller)


rejplots <- rejected_plotttters %>%
  #filter(#rptpro_tipo_concurso == "Otros Interesados" #&
          # Year <=2012
   #      )%>%
  group_by(Year
           )%>%
  summarise(ndvi = mean(NDVI, na.rm = TRUE))%>%
    mutate(award_year = "rejected")%>%
    bind_rows(otros_trendplot_df)%>%
  mutate(early.enroller = ifelse(award_year <= 2012, 1, 0))
  
rejplots$award_year <- as.factor(rejplots$award_year)

rejplots$early_enroller <- as.factor(rejplots$early.enroller)


otrostrend_plot <- ggplot(data = otros_trendplot_df, aes(x = Year, y = ndvi, colour = award_year, linetype = early_enroller)
                                               )+
  geom_path(size = 1)+
  geom_vline(xintercept=2007, linetype = "dashed", color = "black")+
  #geom_vline(xintercept=2010, linetype = "dashed", color = "black")+
  xlim(2005, 2010)+ylim(.815,.865)
otrostrend_plot

ggsave(plot = otrostrend_plot,
       path = "figs",
  filename = "earlytrends.png",
  width = 10,
  units = "in",
  dpi = 500)

shot_trendplot_df <- first_awarded %>%
  group_by(rptpro_tipo_concurso, Year)%>%
  summarise(ndvi = mean(NDVI, na.rm = TRUE))
  
shtrend_plot <- ggplot(data = shot_trendplot_df, aes(x = Year, y = ndvi, colour =rptpro_tipo_concurso))+
  geom_path()
shtrend_plot
```

``` {r awarded panel, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE, eval = TRUE}

ndvi_cohortplot_df <- first_awarded %>%
  filter(Year <= 2008)%>%
  group_by(first.treat, rptpro_tipo_concurso)%>%
  summarise(ndvi = mean(NDVI, na.rm = TRUE))%>%
  rename(award_year = first.treat)

ndvi_cohortplot <- ggplot(data = ndvi_cohortplot_df, aes(x = award_year, y = ndvi, colour = rptpro_tipo_concurso))+
  geom_point()+
  geom_smooth(method='lm', se = FALSE)+
  scale_x_continuous(breaks=c(2009,2011,2013,2015,2017,2019), limits = c(2009,2019))+
  ylim(.805,.845)+
  ggtitle("Early cohorts have higher pre-program NDVI") +
  theme(plot.title = element_text(hjust = 0.5))+
  ylab("pre-2009 NDVI") + xlab("cohort year")
ndvi_cohortplot

# ggsave(plot = ndvi_cohortplot,
#        path = "figs",
#   filename = "ndvi_cohortplot.png",
#   width = 8,
#   units = "in",
#   dpi = 500)

ndvi_cohort <- first_awarded %>%
  mutate(preyear = first.treat - 1)%>%
  filter(Year == preyear)

ndvi_cohort2 <- ndvi_cohort %>%
  group_by(first.treat, rptpro_tipo_concurso)%>%
  summarise(ndvi = mean(NDVI, na.rm = TRUE))%>%
  rename(award_year = first.treat)

ndvi_cohortplot2 <- ggplot(data = ndvi_cohort2, aes(x = award_year, y = ndvi, colour = rptpro_tipo_concurso))+
  geom_point()+
  geom_smooth(method='lm', se = FALSE)+
  scale_x_continuous(breaks=c(2009,2011,2013,2015,2017,2019), limits = c(2009,2019))+
  #ylim(.805,.845)+
  ggtitle("Early cohorts have lower enrollment year NDVI") +
  theme(plot.title = element_text(hjust = 0.5))+
  ylab("enrollment year NDVI") + xlab("cohort year")
ndvi_cohortplot2

# ggsave(plot = ndvi_cohortplot2,
#        path = "figs",
#   filename = "ndvi_cohortplot2.png",
#   width = 8,
#   units = "in",
#   dpi = 500)


trendtest1 <- lm(NDVI~first.treat+as.factor(Year), data = ndvi_cohort)
summary(trendtest1)
  
```

``` {r awarded panel, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE, eval = TRUE}
setwd("C:/Users/garci/Dropbox/chile_reforestation/external_data")

# xls files downloaded from CONAF
#projects
payments_df <- read.csv("concurso_conaf/beneficiarios.csv", header=T)

## define a helper function
empty_as_na <- function(x){
    if("factor" %in% class(x)) x <- as.character(x) ## since ifelse wont work with factors
    ifelse(as.character(x)!="", x, NA)
}

## transform all columns
payments_df <- payments_df %>% 
  mutate_each(funs(empty_as_na))%>%
  rename(rptprop_apellido_paterno = Apellido.paterno.del.beneficiario,
         rptprop_apellido_materno = Apellido.materno.del.beneficiario,
         rptprop_razon_social = Razón.Social..si.receptor.es.persona.jurídica)%>%
  mutate(apellido_ID = group_indices(., rptprop_apellido_paterno, rptprop_apellido_materno),
         unique_ID = group_indices(., rptprop_apellido_paterno, rptprop_apellido_materno, Nombres.del.beneficiario))

all_paid <- NFL_df %>%
  distinct(prop_ID, .keep_all = TRUE)

persons_all_paid <- payments_df %>%
  drop_na(rptprop_apellido_paterno) %>%# 6510 obs
  inner_join(all_paid, by = c("rptprop_apellido_paterno", "rptprop_apellido_materno"))%>%
  group_by(rptprop_apellido_materno, rptprop_apellido_paterno, Nombres.del.beneficiario)%>%
  mutate(namestringd = stringdist(rptprop_nombre, Nombres.del.beneficiario, method = "dl"),
         goodname_ranks = order(order(namestringd, decreasing=FALSE))
         )%>%
  ungroup()%>%
  filter(goodname_ranks ==1 | namestringd <10)%>%
  mutate(paid = 1)%>%
  #select(prop_ID, paid)%>%
  select(rptprop_apellido_materno, rptprop_apellido_paterno, Nombres.del.beneficiario, rptprop_nombre, Nombres.del.beneficiario, rptpro_ano, Acto.por.el.cual.se.otorgó,Fecha.de.Otorgamiento, first.treat, latest.treat)%>%
  distinct()

social_all_paid <- payments_df %>%
  drop_na(rptprop_razon_social) %>%# 537 obs
  inner_join(all_paid, by = "rptprop_razon_social")%>%
  mutate(paid = 1)%>%
  select(prop_ID, paid)%>%
  distinct()

both_paid <- social_all_paid %>%
  bind_rows(persons_all_paid)

new_propp_df <- all_paid %>%
  left_join(both_paid, by = "prop_ID")

new_propp_df$paid[is.na(new_propp_df$paid)] <- 0

sum(new_propp_df$paid)/9086

regpaid_df <- new_propp_df %>%
  filter(first.treat == rptpro_ano)%>%
  mutate(smallholder = ifelse(rptpro_tipo_concurso != "Otros Interesados", 1, 0))

reforest_tipo <- lm(reforestation2 ~ as.factor(rptpro_tipo_concurso), data = NFL_df)

f <- lm(paid~smallholder+reforestation2+rptpro_monto_total+rptpre_superficie_bonificada+rptpro_puntaje+as.factor(first.treat), data = regpaid_df)
summary(f)

table(regpaid_df$paid)



length(unique(payments_df$apellido_ID))/9078#4082/31.36%
length(unique(payments_df$unique_ID))/9078#20847/44.97%

library(stargazer)
stargazer(f)

```

```{r}
persons_payments <- payments_df %>%
  drop_na(rptprop_apellido_paterno) %>%# 6510 obs
  inner_join(rolarea_df, by = c("rptprop_apellido_paterno", "rptprop_apellido_materno"))%>%
  group_by(rptprop_apellido_materno, rptprop_apellido_paterno, Nombres.del.beneficiario)%>%
  mutate(namestringd = stringdist(rptprop_nombre, Nombres.del.beneficiario, method = "dl"),
         goodname_ranks = order(order(namestringd, decreasing=FALSE))
         )%>%
  ungroup()%>%
  filter(goodname_ranks ==1 | namestringd <10)%>%
  mutate(paid = 1)%>%
  select(prop_ID, paid)%>%
  distinct()
  

social_payments <- payments_df %>%
  drop_na(rptprop_razon_social) %>%# 537 obs
  inner_join(property_df, by = "rptprop_razon_social")%>%
  mutate(paid = 1)%>%
  select(prop_ID, paid)%>%
  distinct()

payments <- social_payments %>%
  bind_rows(persons_payments)
  
  

new_rolarea_df <- rolarea_df %>%
  left_join(payments, by = "prop_ID")

new_rolarea_df$paid[is.na(new_rolarea_df$paid)] <- 0
sum(new_rolarea_df$paid)/3272# 672 of 3272 paid/ 
# 20.54%

paidrol <- new_rolarea_df %>%
  #filter(first.treat == rptpro_ano)%>%
  mutate(smallholder = ifelse(rptpro_tipo_concurso != "Otros Interesados", 1, 0))


sh_paid <- new_rolarea_df %>%
  filter(first.treat == rptpro_ano & 
           rptpro_tipo_concurso != "Otros Interesados")

paid_diff <- lm(paid~smallholder+reforestation2+rptpro_puntaje+as.factor(first.treat), data = paidrol)
summary(paid_diff)
stargazer(f, paid_diff)



```

``` {r awarded panel, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE, eval = TRUE}

new_first_awarded <- awarded_ndvi %>%
  inner_join(new_rolarea_df, by = "prop_ID") %>%
  filter(first.treat == rptpro_ano) %>%
  distinct(Year, prop_ID, .keep_all = TRUE)

paid_trendplot_df <- new_first_awarded %>%
  #filter(first.treat ==2011| first.treat ==2014 | first.treat ==2018)%>% 
  #filter(rptpro_tipo_concurso == "Otros Interesados")%>%
  group_by(rptpro_tipo_concurso, paid, Year)%>%
  summarise(ndvi = mean(NDVI, na.rm = TRUE))#%>%
 # rename(award_year = first.treat)
paid_trendplot_df$paid <- as.character(paid_trendplot_df$paid)
#paid_trendplot_df$award_year <- as.character(paid_trendplot_df$award_year)

paidtrend_plot <- ggplot(data = paid_trendplot_df, aes(x = Year, y = ndvi, linetype = paid, colour = rptpro_tipo_concurso
                                                       ))+
  geom_path()
paidtrend_plot



```





