---
  title: "matching pool generation"
#author: "Albert Garcia"
output:
  pdf_document:
  number_sections: yes
toc: no
fontsize: 11pt    
documentclass: article
geometry: margin=1in
header-includes: 
  \usepackage{sectsty}
\usepackage{enumitem}
\usepackage{comment}
\usepackage{multirow,array}
\usepackage{makecell}
\usepackage{dcolumn}
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(out.height='300px', dpi=200)

### loads packages
library(latex2exp)
library(tidyverse)
library(ggplot2)
library(sf)
library(stringi)
library(data.table)
library(fuzzyjoin)
library(stringdist)
library(rio)

```

``` {r submitted mp, echo = FALSE, message = FALSE, warning = FALSE, include = FALSE, eval = TRUE}

forestlaw_df <- readRDS("C:/Users/garci/Dropbox/chile_reforestation/data/submittedmp_analysis/NFL_df.rds")
my_covars <- data.frame(readRDS("C:/Users/garci/Dropbox/chile_reforestation/data/property_covariates/my_covars.rds"))
all_geoms <- readRDS("C:/Users/garci/Dropbox/chile_reforestation/data/submittedmp_analysis/all_geoms.rds")
used_geoms <- readRDS("C:/Users/garci/Dropbox/chile_reforestation/data/submittedmp_analysis/used_geoms.rds")
exclude_match <- all_geoms



```

```{r, message = FALSE}
setwd("C:/Users/garci/Dropbox/chile_reforestation/data/property_ndvi/new_CIREN_ndvi/enrolled/ndvi")

# load ndvi time series for all submitted properties
temp = list.files(pattern="*.csv")
my_ndvi = bind_rows(lapply(temp, read_csv))%>%
  select(prop_ID, year, mean) %>%
  distinct(prop_ID, year, .keep_all = TRUE) %>%
  mutate(year = paste0("y_", year))%>%
  spread(key = "year", value = "mean")# cast ndvi into wide format
```

```{r, message = FALSE}
setwd("C:/Users/garci/Dropbox/chile_reforestation/data/property_ndvi/new_CIREN_ndvi/enrolled/evi2")

# load evi time series for all matched properties
temp = list.files(pattern="*.csv")
my_evi = bind_rows(lapply(temp, read_csv))%>%
  select(prop_ID, year, mean) %>%
  distinct(prop_ID, year, .keep_all = TRUE) %>%
  mutate(year = paste0("evi_", year))%>%
  spread(key = "year", value = "mean")# cast into wide format

my_match <- my_covars %>%
  inner_join(used_geoms, by = "prop_ID")%>%
  inner_join(my_ndvi, by = "prop_ID")%>%
  inner_join(my_evi, by = "prop_ID")
```

```{r}

export(my_match, "my_match.rds")

```

``` {r los rios match pool, echo = FALSE, message = FALSE, warning = FALSE, include = FALSE, eval = TRUE}
setwd("C:/Users/garci/Dropbox/chile_reforestation/data/property_ndvi/new_CIREN_ndvi/match/losrios")

# load los rios ndvi time series for all ciren properties
temp = list.files(pattern="*.csv")
losrios_ndvi = bind_rows(lapply(temp, read_csv))%>%
  select(objectid, year, mean) %>%
  distinct(objectid, year, .keep_all = TRUE) %>%
  mutate(year = paste0("y_", year))%>%
  spread(key = "year", value = "mean")# cast ndvi into wide format
```

```{r}
setwd("C:/Users/garci/Dropbox/chile_reforestation/data/property_ndvi/new_CIREN_ndvi/match_evi/losrios_evi")

# load los rios ndvi time series for all ciren properties
temp = list.files(pattern="*.csv")
losrios_evi = bind_rows(lapply(temp, read_csv))%>%
  select(objectid, year, mean) %>%
  distinct(objectid, year, .keep_all = TRUE) %>%
  mutate(year = paste0("evi_", year))%>%
  spread(key = "year", value = "mean")# cast ndvi into wide format

# to make sure I'm not selecting treated properties
# disjoint join los Rios CIREN properties with property df based

losrios_ciren <-  st_read(
  "C:/Users/garci/Dropbox/chile_reforestation/external_data/ciren_simef/PROPIEDADES_RURALES/LOS_RÍOS_CIREN_2018.shp"
)%>%
  st_make_valid()

losrios_matchpool <- losrios_ciren[!lengths(st_intersects(losrios_ciren, st_make_valid(exclude_match))), ] %>%
  #st_join(mgmtplan_df, join = st_disjoint)%>%
  inner_join(data.frame(readRDS("C:/Users/garci/Dropbox/chile_reforestation/data/property_covariates/losrios_CIREN_covars.rds")), by = c("objectid", "rol", "desccomu"))%>%
  inner_join(losrios_ndvi, by = "objectid")%>%
  inner_join(losrios_evi, by = "objectid")


```

``` {r biobio ndvi, echo = FALSE, message = FALSE, warning = FALSE, include = FALSE, eval = TRUE}
setwd("C:/Users/garci/Dropbox/chile_reforestation/data/property_ndvi/new_CIREN_ndvi/match/biobio")

# load biobio ndvi time series for all ciren properties
temp = list.files( pattern="*.csv")
biobio_ndvi = bind_rows(lapply(temp, read_csv))%>%
  #filter(objectid == 59515) %>%
  select(objectid, year, mean) %>%
  distinct(objectid, year, .keep_all = TRUE) %>%
  mutate(year = paste0("y_", year))%>%
  spread(key = "year", value = "mean")# cast ndvi into wide format

```

``` {r biobio ndvi, echo = FALSE, message = FALSE, warning = FALSE, include = FALSE, eval = TRUE}
setwd("C:/Users/garci/Dropbox/chile_reforestation/data/property_ndvi/new_CIREN_ndvi/match_evi/biobio_evi")

# load biobio ndvi time series for all ciren properties
temp = list.files( pattern="*.csv")
biobio_evi = bind_rows(lapply(temp, read_csv))%>%
  #filter(objectid == 59515) %>%
  select(objectid, year, mean) %>%
  distinct(objectid, year, .keep_all = TRUE) %>%
  mutate(year = paste0("evi_", year))%>%
  spread(key = "year", value = "mean")# cast ndvi into wide format

```

```{r}
setwd("C:/Users/garci/Dropbox/chile_reforestation/data/property_ndvi/new_CIREN_ndvi/match/nuble")

# add nuble ndvi time series for all ciren properties
temp = list.files(pattern="*.csv")
biobionuble_ndvi = bind_rows(lapply(temp, read_csv))%>%
  select(objectid, year, mean) %>%
  distinct(objectid, year, .keep_all = TRUE) %>%
  mutate(year = paste0("y_", year))%>%
  spread(key = "year", value = "mean")%>%# cast ndvi into wide format%>%
  bind_rows(biobio_ndvi)
```

``` {r biobio ndvi, echo = FALSE, message = FALSE, warning = FALSE, include = FALSE, eval = TRUE}
setwd("C:/Users/garci/Dropbox/chile_reforestation/data/property_ndvi/new_CIREN_ndvi/match_evi/nuble_evi")

# load biobio ndvi time series for all ciren properties
temp = list.files( pattern="*.csv")
biobionuble_evi = bind_rows(lapply(temp, read_csv))%>%
  #filter(objectid == 59515) %>%
  select(objectid, year, mean) %>%
  distinct(objectid, year, .keep_all = TRUE) %>%
  mutate(year = paste0("evi_", year))%>%
  spread(key = "year", value = "mean")%>%
  bind_rows(biobio_evi)


# to make sure I'm not selecting treated properties
# join los Rios CIREN properties with property df based on rol

biobionuble_ciren <-  st_read(
  "C:/Users/garci/Dropbox/chile_reforestation/external_data/ciren_simef/PROPIEDADES_RURALES/BIOBÍO_CIREN_2016.shp"
) %>%
  st_make_valid()
biobionuble_matchpool <- biobionuble_ciren[!lengths(st_intersects(biobionuble_ciren, st_make_valid(exclude_match))), ] %>%
  #st_join(mgmtplan_df, join = st_disjoint)%>%
  inner_join(data.frame(readRDS("C:/Users/garci/Dropbox/chile_reforestation/data/property_covariates/biobionuble_CIREN_covars.rds")), by = c("objectid", "rol", "desccomu"))%>%
  inner_join(biobionuble_ndvi, by = "objectid")%>%
  inner_join(biobionuble_evi, by = "objectid")

```

``` {r maule, echo = FALSE, message = FALSE, warning = FALSE, include = FALSE, eval = TRUE}
setwd("C:/Users/garci/Dropbox/chile_reforestation/data/property_ndvi/new_CIREN_ndvi/match/maule")
# load maule ndvi time series for all ciren properties
temp = list.files( pattern="*.csv")
maule_ndvi = bind_rows(lapply(temp, read_csv))%>%
  #filter(objectid == 59515) %>%
  select(objectid, year, mean) %>%
  distinct(objectid, year, .keep_all = TRUE) %>%
  mutate(year = paste0("y_", year))%>%
  spread(key = "year", value = "mean")# cast ndvi into wide format

```

```{r}

setwd("C:/Users/garci/Dropbox/chile_reforestation/data/property_ndvi/new_CIREN_ndvi/match_evi/maule_evi")
# load maule ndvi time series for all ciren properties
temp = list.files( pattern="*.csv")
maule_evi = bind_rows(lapply(temp, read_csv))%>%
  #filter(objectid == 59515) %>%
  select(objectid, year, mean) %>%
  distinct(objectid, year, .keep_all = TRUE) %>%
  mutate(year = paste0("evi_", year))%>%
  spread(key = "year", value = "mean")# cast ndvi into wide format

# to make sure I'm not selecting treated properties
maule_ciren <-  st_read(
  "C:/Users/garci/Dropbox/chile_reforestation/external_data/ciren_simef/PROPIEDADES_RURALES/MAULE_CIREN_2014.shp"
)  %>%
  st_make_valid()
maule_matchpool <- maule_ciren[!lengths(st_intersects(maule_ciren, st_make_valid(exclude_match))), ] %>%
  #st_join(mgmtplan_df, join = st_disjoint)%>%
  inner_join(data.frame(readRDS("C:/Users/garci/Dropbox/chile_reforestation/data/property_covariates/maule_CIREN_covars.rds")), by = c("objectid", "rol", "desccomu"))%>%
  inner_join(maule_ndvi, by = "objectid")%>%
  inner_join(maule_evi, by = "objectid")


```

``` {r araucania, echo = FALSE, message = FALSE, warning = FALSE, include = FALSE, eval = TRUE}
setwd("C:/Users/garci/Dropbox/chile_reforestation/data/property_ndvi/new_CIREN_ndvi/match/araucania")
# load araucania ndvi time series for all ciren properties
temp = list.files( pattern="*.csv")
araucania_ndvi = bind_rows(lapply(temp, read_csv))%>%
  select(objectid, year, mean) %>%
  distinct(objectid, year, .keep_all = TRUE) %>%
  mutate(year = paste0("y_", year))%>%
  spread(key = "year", value = "mean")# cast ndvi into wide format
```

```{r}
setwd("C:/Users/garci/Dropbox/chile_reforestation/data/property_ndvi/new_CIREN_ndvi/match_evi/araucania_evi")
# load araucania ndvi time series for all ciren properties
temp = list.files( pattern="*.csv")
araucania_evi = bind_rows(lapply(temp, read_csv))%>%
  select(objectid, year, mean) %>%
  distinct(objectid, year, .keep_all = TRUE) %>%
  mutate(year = paste0("evi_", year))%>%
  spread(key = "year", value = "mean")# cast ndvi into wide format

# to make sure I'm not selecting treated properties
# to make sure I'm not selecting treated properties
araucania_ciren <-  st_read(
  "C:/Users/garci/Dropbox/chile_reforestation/external_data/ciren_simef/PROPIEDADES_RURALES/ARAUCANÍA_CIREN_2013.shp"
)  %>%
  st_make_valid()

araucania_matchpool <- araucania_ciren[!lengths(st_intersects(araucania_ciren, st_make_valid(exclude_match))), ] %>%
  #st_join(mgmtplan_df, join = st_disjoint)%>%
  inner_join(data.frame(readRDS("C:/Users/garci/Dropbox/chile_reforestation/data/property_covariates/araucania_CIREN_covars.rds")), by = c("objectid", "rol", "desccomu"))%>%
  inner_join(araucania_ndvi, by = "objectid")%>%
  inner_join(araucania_evi, by = "objectid")


```

``` {r los lagos, echo = FALSE, message = FALSE, warning = FALSE, include = FALSE, eval = TRUE}

setwd("C:/Users/garci/Dropbox/chile_reforestation/data/property_ndvi/new_CIREN_ndvi/match/loslagos")
# load los lagos ndvi time series for all ciren properties
temp = list.files( pattern="*.csv")
loslagos_ndvi = bind_rows(lapply(temp, read_csv))%>%
  select(objectid, year, mean) %>%
  distinct(objectid, year, .keep_all = TRUE) %>%
  mutate(year = paste0("y_", year))%>%
  spread(key = "year", value = "mean")# cast ndvi into wide format

```


```{r}
setwd("C:/Users/garci/Dropbox/chile_reforestation/data/property_ndvi/new_CIREN_ndvi/match_evi/loslagos_evi")
# load araucania ndvi time series for all ciren properties
temp = list.files( pattern="*.csv")
loslagos_evi = bind_rows(lapply(temp, read_csv))%>%
  select(objectid, year, mean) %>%
  distinct(objectid, year, .keep_all = TRUE) %>%
  mutate(year = paste0("evi_", year))%>%
  spread(key = "year", value = "mean")# cast ndvi into wide format


# to make sure I'm not selecting treated properties
# to make sure I'm not selecting treated properties
loslagos_ciren <-  st_read(
  "C:/Users/garci/Dropbox/chile_reforestation/external_data/ciren_simef/PROPIEDADES_RURALES/LOS_LAGOS_CIREN_2016.shp"
)  %>%
  st_make_valid()
loslagos_matchpool <- loslagos_ciren[!lengths(st_intersects(loslagos_ciren, st_make_valid(exclude_match))), ] %>%
  #st_join(mgmtplan_df, join = st_disjoint)%>%
  inner_join(data.frame(readRDS("C:/Users/garci/Dropbox/chile_reforestation/data/property_covariates/loslagos_CIREN_covars.rds")), by = c("objectid", "rol", "desccomu"))%>%
  inner_join(loslagos_ndvi, by = "objectid")%>%
  inner_join(loslagos_evi, by = "objectid")

```

``` {r ohiggins, echo = FALSE, message = FALSE, warning = FALSE, include = FALSE, eval = TRUE}

setwd("C:/Users/garci/Dropbox/chile_reforestation/data/property_ndvi/new_CIREN_ndvi/match/ohiggins")
# load araucania ndvi time series for all ciren properties
temp = list.files( pattern="*.csv")
ohiggins_ndvi = bind_rows(lapply(temp, read_csv))%>%
  select(objectid, year, mean) %>%
  distinct(objectid, year, .keep_all = TRUE) %>%
  mutate(year = paste0("y_", year))%>%
  spread(key = "year", value = "mean")# cast ndvi into wide format
```


```{r}
setwd("C:/Users/garci/Dropbox/chile_reforestation/data/property_ndvi/new_CIREN_ndvi/match_evi/ohiggins_evi")
# load araucania ndvi time series for all ciren properties
temp = list.files( pattern="*.csv")
ohiggins_evi = bind_rows(lapply(temp, read_csv))%>%
  select(objectid, year, mean) %>%
  distinct(objectid, year, .keep_all = TRUE) %>%
  mutate(year = paste0("evi_", year))%>%
  spread(key = "year", value = "mean")# cast ndvi into wide format

# to make sure I'm not selecting treated properties
# to make sure I'm not selecting treated properties
ohiggins_ciren <-  st_read(
  "C:/Users/garci/Dropbox/chile_reforestation/external_data/ciren_simef/PROPIEDADES_RURALES/LIBERTADOR_GENERAL_BERNARDO_O_HIGGINS_CIREN_2013.shp"
)  %>%
  st_make_valid()
ohiggins_matchpool <- ohiggins_ciren[!lengths(st_intersects(ohiggins_ciren, st_make_valid(exclude_match))), ] %>%
  #st_join(mgmtplan_df, join = st_disjoint)%>%
  inner_join(data.frame(readRDS("C:/Users/garci/Dropbox/chile_reforestation/data/property_covariates/ohiggins_CIREN_covars.rds")), by = c("objectid", "rol", "desccomu"))%>%
  inner_join(ohiggins_ndvi, by = "objectid")%>%
  inner_join(ohiggins_evi, by = "objectid")

```

```{r}

variabler <- function(df){
  return_df <- df %>%
    mutate(treat=0,
         first.treat = 0,
         forest = c_1,
         plantation = c_3,
         baresoil = c_12,
         pasture = c_9,
         shrub = c_5,
         water = c_15,
         urban = c_16)%>%
  select(objectid, geometry.x, treat, first.treat, property_area_ha, road_dist, lat, long, slope, elev, treat, forest, plantation, water, shrub, baresoil, pasture, urban, proportion_erosion, mod_to_severe_erosion_area, industry_dist, native_industry_dist, y_2005:y_2020, evi_2005:evi_2020)

 return(return_df)
}

all_matchpool <- variabler(losrios_matchpool) %>%
  rbind(variabler(maule_matchpool))%>%
  rbind(variabler(araucania_matchpool))%>%
  rbind(variabler(biobionuble_matchpool))%>%
  rbind(variabler(loslagos_matchpool))%>%
  rbind(variabler(ohiggins_matchpool))%>%
  mutate(controlid = 1:nrow(.))%>%
  rename(geometry=geometry.x)

export(all_matchpool, "all_matchpool.rds")

```


