---
title: "matching"
#author: "Albert Garcia"
output:
  pdf_document:
    number_sections: yes
    toc: no
fontsize: 11pt    
documentclass: article
geometry: margin=1in
header-includes: 
  \usepackage{sectsty}
  \usepackage{enumitem}
  \usepackage{comment}
  \usepackage{multirow,array}
  \usepackage{makecell}
  \usepackage{dcolumn}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(out.height='300px', dpi=200)

### loads packages
library(latex2exp)
library(tidyverse)
library(ggplot2)
library(sf)
library(stringi)
library(data.table)
library(fuzzyjoin)
library(stringdist)

```


```{r}

enrolled_df <- readRDS("enrolled_df.rds")
all_matchpool <- readRDS("all_matchpool.rds")

```

```{r}
# combining regional matchpools and treatedmatches
# propertypaid_id <- readRDS("propertypaid_id.rds")
# 
enrollees <- enrolled_df %>%
  mutate(treat = 1,
         forest = c_1,
         plantation = c_3,
         baresoil = c_10+c_12,
         pasture = c_9,
         shrub = c_5,
         water = c_15,
         urban = c_16,
         smallholder = ifelse(rptpro_tipo_concurso == "Otros Interesados", 0, 1))#%>%
#   select(rptpro_puntaje, smallholder, rptpre_superficie_bonificada, rptpro_tipo_concurso, rptpre_monto_total, rptpre_region, desccomu, rptprop_sexo, prop_ID, first.treat, treated.later, rptprop_etnia, rptpro_objetivo_manejo.x, area_ha, reforestation2, reforestation, reffirst.treat, ref2first.treat, area_prop, road_dist, lat, long, slope, elev, treat, forest, plantation, water, baresoil, shrub, pasture, urban, y_2005, y_2006, y_2007, y_2008, y_2009, y_2010, y_2011, y_2012, y_2013, y_2014, y_2015, y_2016, y_2017, y_2018, y_2019, y_2020)%>%
#   left_join(propertypaid_id, by = "prop_ID")%>%
#   mutate(paid = ifelse(is.na(paid), 0, paid))

# summary(enrollees$paid)


df <- data.frame(enrollees)%>%
  bind_rows(all_matchpool)%>%
  mutate(trend1918 = y_2019 - y_2018,
         trend1817 = y_2018 - y_2017,
         trend1716 = y_2017 - y_2016,
         trend1615 = y_2016 - y_2015,
         trend1514 = y_2015 - y_2014,
         trend1413 = y_2014 - y_2013,
         trend1312 = y_2013 - y_2012,
         trend1211 = y_2012 - y_2011,
         trend1110 = y_2011 - y_2010,
         trend1009 = y_2010 - y_2009,
         trend0908 = y_2009 - y_2008,
         trend0807 = y_2008 - y_2007,
         trend0706 = y_2007 - y_2006,
         trend0605 = y_2006 - y_2005,
         road_dist = unlist(road_dist))
library(rio)
export(df, "matching_df.rds")


```

```{r}
library(MatchIt)
# create matched dataframes
df <- readRDS("matching_df.rds")

df <- df %>%
  drop_na(elev, slope)
  
#love.plot(matched_2009, thresholds = c(m = .25))


matched_2009 <- matchit(treat ~ trend0807 + trend0706 + trend0605 + y_2007
                        + forest + plantation + baresoil + pasture + urban +water + slope + elev  + area_ha + road_dist, 
                   data = subset(df, first.treat == 0 | first.treat == 2009),
                 method = "nearest")#, ratio = 2)

matched_2010 <- matchit(treat ~ trend0908 + trend0807 + trend0706  +trend0605 
                        + y_2007
                        + forest + plantation + baresoil + pasture + urban +water+ slope + elev  + area_ha + road_dist, 
                   data = subset(df, first.treat == 0 | first.treat == 2010),
                 method = "nearest")#, ratio = 2)

matched_2011 <- matchit(treat ~ trend1009 + trend0908 + trend0807 + trend0706 +trend0605 
                        + y_2007 
                        + forest + plantation + baresoil + pasture  + urban +water+ slope + elev  + area_ha + road_dist, 
                   data = subset(df, first.treat == 0 | first.treat == 2011),
                 method = "nearest")#, ratio = 2)

matched_2012 <- matchit(treat ~ trend1110 + trend1009 + trend0908 + trend0807+ trend0706 
                        + y_2007 
                        +forest + plantation + baresoil + pasture  + urban +water+ slope + elev  + area_ha + road_dist, 
                   data = subset(df, first.treat == 0 | first.treat == 2012),
                 method = "nearest")#, ratio = 2)

matched_2013 <- matchit(treat ~ trend1211 + trend1110 + trend1009 + trend0908 +trend0807
                        + y_2007
                        + forest + plantation + baresoil + pasture + urban +water+ slope + elev  + area_ha + road_dist, 
                   data = subset(df, first.treat == 0 | first.treat == 2013),
                 method = "nearest")#, ratio = 2)

matched_2014 <- matchit(treat ~ trend1312 + trend1211 + trend1110 + trend1009 + trend0908
                        + y_2007 
                        + forest + plantation + baresoil + pasture + urban +water+ slope + elev  + area_ha + road_dist, 
                   data = subset(df, first.treat == 0 | first.treat == 2014),
                 method = "nearest")#, ratio = 2)

matched_2015 <- matchit(treat ~ trend1413 + trend1312 + trend1211 + trend1110 + trend1009 
                        + y_2007
                        + forest + plantation + baresoil + pasture  + urban +water+ slope + elev  + area_ha + road_dist, 
                   data = subset(df, first.treat == 0 | first.treat == 2015),
                 method = "nearest")#, ratio = 2)

matched_2016 <- matchit(treat ~ trend1514 + trend1413 + trend1312 + trend1211 + trend1110
                        +  y_2007
                        + forest + plantation + baresoil + pasture +urban +water+ slope + elev  + area_ha + road_dist, 
                   data = subset(df, first.treat == 0 | first.treat == 2016),
                 method = "nearest")#, ratio = 2)

matched_2017 <- matchit(treat ~ trend1615 + trend1514 + trend1413 + trend1312 + trend1211
                        +  y_2007
                        + forest + plantation + baresoil + pasture + urban +water+ slope + elev  + area_ha + road_dist, 
                   data = subset(df, first.treat == 0 | first.treat == 2017),
                 method = "nearest")#, ratio = 2)

matched_2018 <- matchit(treat ~ trend1716 + trend1615 + trend1514 + trend1413 + trend1312 
                        +  y_2007
                        + forest + plantation + baresoil + pasture + urban +water+ slope + elev  + area_ha + road_dist, 
                   data = subset(df, first.treat == 0 | first.treat == 2018),
                 method = "nearest")#, ratio = 2)

matched_2019 <- matchit(treat ~ trend1817 + trend1716 + trend1615 + trend1514 + trend1413 
                        + y_2007
                        + forest + plantation + baresoil + pasture+ urban +water+ slope + elev  + area_ha + road_dist, 
                   data = subset(df, first.treat == 0 | first.treat == 2019),
                 method = "nearest")#, ratio = 2)

map_covars <- function(df){
  return_df <- within(df, quartile <- as.integer(cut(rptpro_puntaje, quantile(rptpro_puntaje, probs=0:4/4, na.rm = TRUE), include.lowest=TRUE)))
  
    return_df <- return_df %>%
    group_by(subclass)%>%
    mutate(smallholder = max(smallholder, na.rm = TRUE),
         reforestation = max(reforestation, na.rm = TRUE),
         reforestation2 = max(reforestation2, na.rm = TRUE),
         area_prop = max(area_prop, na.rm = TRUE),
         did_group = max(first.treat, na.rm = TRUE),
         quartile = max(quartile, na.rm = TRUE)
         )%>%
    ungroup()
  
 return(return_df)
}


# group by matched pairs
matched_wide <- map_covars(match.data(matched_2009, subclass = "subclass"))%>%
  bind_rows(map_covars(match.data(matched_2010, subclass = "subclass")))%>%
  bind_rows(map_covars(match.data(matched_2011, subclass = "subclass")))%>%
  bind_rows(map_covars(match.data(matched_2012, subclass = "subclass")))%>%
  bind_rows(map_covars(match.data(matched_2013, subclass = "subclass")))%>%
  bind_rows(map_covars(match.data(matched_2014, subclass = "subclass")))%>%
  bind_rows(map_covars(match.data(matched_2015, subclass = "subclass")))%>%
  bind_rows(map_covars(match.data(matched_2016, subclass = "subclass")))%>%
  bind_rows(map_covars(match.data(matched_2017, subclass = "subclass")))%>%
  bind_rows(map_covars(match.data(matched_2018, subclass = "subclass")))%>%
  bind_rows(map_covars(match.data(matched_2019, subclass = "subclass")))%>%
  mutate(id = 1:nrow(.))%>%
  distinct(objectid, prop_ID, .keep_all = TRUE)

baltest_covs <- subset(matched_wide, select = c("forest" ,"plantation" , "baresoil", "pasture", "urban", "water", "slope", "elev", "area_ha", "road_dist", "y_2007"))
library(cobalt)
bal_match <- bal.tab(baltest_covs, treat = matched_wide$treat,thresholds = c(m = .25))[[1]][,2:3]

baltestun_covs <- subset(df, select = c("forest" ,"plantation" , "baresoil", "pasture", "urban", "water", "slope", "elev", "area_ha", "road_dist", "y_2007"))

# bal_test.tbl <- cbind(bal_match, bal.tab(baltestun_covs, treat = df$treat,thresholds = c(m = .25))[[1]][,2:3])%>%
#   rownames_to_column(var = "covariate")%>%
#   rename(unmatched = 4,
#          matched = 2)
# 
# export(bal_test.tbl, "covariate_balance.rds")

library(kableExtra)


matched_long <- gather(matched_wide, "Year", "NDVI", y_2005:y_2020)%>%
  separate(Year, , into = c(NA, "Year"), sep = "_")

#export(matched_long, "enrolled_analysis_ratio1unique.rds")

```

```{r ratio 2}
library(MatchIt)
# create matched dataframes
df <- readRDS("matching_df.rds")

df <- df %>%
  drop_na(elev, slope)
  
#love.plot(matched_2009, thresholds = c(m = .25))


matched_2009 <- matchit(treat ~ trend0807 + trend0706 + trend0605 + y_2007
                        + forest + plantation + baresoil + pasture + urban +water + slope + elev  + area_ha + road_dist, 
                   data = subset(df, first.treat == 0 | first.treat == 2009),
                 method = "nearest", ratio = 2)

matched_2010 <- matchit(treat ~ trend0908 + trend0807 + trend0706  +trend0605 
                        + y_2007
                        + forest + plantation + baresoil + pasture + urban +water+ slope + elev  + area_ha + road_dist, 
                   data = subset(df, first.treat == 0 | first.treat == 2010),
                 method = "nearest", ratio = 2)

matched_2011 <- matchit(treat ~ trend1009 + trend0908 + trend0807 + trend0706 +trend0605 
                        + y_2007 
                        + forest + plantation + baresoil + pasture  + urban +water+ slope + elev  + area_ha + road_dist, 
                   data = subset(df, first.treat == 0 | first.treat == 2011),
                 method = "nearest", ratio = 2)

matched_2012 <- matchit(treat ~ trend1110 + trend1009 + trend0908 + trend0807+ trend0706 
                        + y_2007 
                        +forest + plantation + baresoil + pasture  + urban +water+ slope + elev  + area_ha + road_dist, 
                   data = subset(df, first.treat == 0 | first.treat == 2012),
                 method = "nearest", ratio = 2)

matched_2013 <- matchit(treat ~ trend1211 + trend1110 + trend1009 + trend0908 +trend0807
                        + y_2007
                        + forest + plantation + baresoil + pasture + urban +water+ slope + elev  + area_ha + road_dist, 
                   data = subset(df, first.treat == 0 | first.treat == 2013),
                 method = "nearest", ratio = 2)

matched_2014 <- matchit(treat ~ trend1312 + trend1211 + trend1110 + trend1009 + trend0908
                        + y_2007 
                        + forest + plantation + baresoil + pasture + urban +water+ slope + elev  + area_ha + road_dist, 
                   data = subset(df, first.treat == 0 | first.treat == 2014),
                 method = "nearest", ratio = 2)

matched_2015 <- matchit(treat ~ trend1413 + trend1312 + trend1211 + trend1110 + trend1009 
                        + y_2007
                        + forest + plantation + baresoil + pasture  + urban +water+ slope + elev  + area_ha + road_dist, 
                   data = subset(df, first.treat == 0 | first.treat == 2015),
                 method = "nearest", ratio = 2)

matched_2016 <- matchit(treat ~ trend1514 + trend1413 + trend1312 + trend1211 + trend1110
                        +  y_2007
                        + forest + plantation + baresoil + pasture +urban +water+ slope + elev  + area_ha + road_dist, 
                   data = subset(df, first.treat == 0 | first.treat == 2016),
                 method = "nearest", ratio = 2)

matched_2017 <- matchit(treat ~ trend1615 + trend1514 + trend1413 + trend1312 + trend1211
                        +  y_2007
                        + forest + plantation + baresoil + pasture + urban +water+ slope + elev  + area_ha + road_dist, 
                   data = subset(df, first.treat == 0 | first.treat == 2017),
                 method = "nearest", ratio = 2)

matched_2018 <- matchit(treat ~ trend1716 + trend1615 + trend1514 + trend1413 + trend1312 
                        +  y_2007
                        + forest + plantation + baresoil + pasture + urban +water+ slope + elev  + area_ha + road_dist, 
                   data = subset(df, first.treat == 0 | first.treat == 2018),
                 method = "nearest", ratio = 2)

matched_2019 <- matchit(treat ~ trend1817 + trend1716 + trend1615 + trend1514 + trend1413 
                        + y_2007
                        + forest + plantation + baresoil + pasture+ urban +water+ slope + elev  + area_ha + road_dist, 
                   data = subset(df, first.treat == 0 | first.treat == 2019),
                 method = "nearest", ratio = 2)


map_covars <- function(df){
  return_df <- within(df, quartile <- as.integer(cut(rptpro_puntaje, quantile(rptpro_puntaje, probs=0:4/4, na.rm = TRUE), include.lowest=TRUE)))
  
    return_df <- return_df %>%
    group_by(subclass)%>%
    mutate(smallholder = max(smallholder, na.rm = TRUE),
         reforestation = max(reforestation, na.rm = TRUE),
         reforestation2 = max(reforestation2, na.rm = TRUE),
         area_prop = max(area_prop, na.rm = TRUE),
         did_group = max(first.treat, na.rm = TRUE),
         quartile = max(quartile, na.rm = TRUE)
         )%>%
    ungroup()
  
 return(return_df)
}

# group by matched pairs
matched_wide_2 <- map_covars(match.data(matched_2009, subclass = "subclass"))%>%
  bind_rows(map_covars(match.data(matched_2010, subclass = "subclass")))%>%
  bind_rows(map_covars(match.data(matched_2011, subclass = "subclass")))%>%
  bind_rows(map_covars(match.data(matched_2012, subclass = "subclass")))%>%
  bind_rows(map_covars(match.data(matched_2013, subclass = "subclass")))%>%
  bind_rows(map_covars(match.data(matched_2014, subclass = "subclass")))%>%
  bind_rows(map_covars(match.data(matched_2015, subclass = "subclass")))%>%
  bind_rows(map_covars(match.data(matched_2016, subclass = "subclass")))%>%
  bind_rows(map_covars(match.data(matched_2017, subclass = "subclass")))%>%
  bind_rows(map_covars(match.data(matched_2018, subclass = "subclass")))%>%
  bind_rows(map_covars(match.data(matched_2019, subclass = "subclass")))%>%
  mutate(id = 1:nrow(.))%>%
  distinct(objectid, prop_ID, .keep_all = TRUE)

baltest_covs2 <- subset(matched_wide_2, select = c("forest" ,"plantation" , "baresoil", "pasture", "urban", "water", "slope", "elev", "area_ha", "road_dist", "y_2007"))
library(cobalt)
bal_match2 <- bal.tab(baltest_covs2, treat = matched_wide_2$treat,thresholds = c(m = .25))[[1]][,2:3]


baltestun_covs <- subset(df, select = c("forest" ,"plantation" , "baresoil", "pasture", "urban", "water", "slope", "elev", "area_ha", "road_dist", "y_2007"))

# bal_test.tbl <- bal_match %>%
#   cbind(
#     cbind(bal_match2, bal.tab(baltestun_covs, treat = df$treat,thresholds = c(m = .25))[[1]][,2:3])
#     )%>%
#   rownames_to_column(var = "covariate")%>%
#   rename(unmatched = 6,
#          matched_2 = 4,
#          matched =2)

#export(bal_test.tbl, "covariate_balance.rds")

library(kableExtra)


matched_long_2 <- gather(matched_wide_2, "Year", "NDVI", y_2005:y_2020)%>%
  separate(Year, into = c(NA, "Year"), sep = "_")

#export(matched_long_2, "enrolled_analysis_ratio2unique.rds")


```


```{r}

mytheme <- theme(legend.position = "none", plot.title = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank())

bottom_theme <- theme(legend.position="bottom",plot.title = element_blank(), legend.title = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank())


# density plots for matched data
den_m_plantation <- bal.plot(baltest_covs2, treat = matched_wide_2$treat, var.name = "plantation", sample.names = "matched (r=2)" )+mytheme
den_m_forest <- bal.plot(baltest_covs2, treat = matched_wide_2$treat, var.name = "forest", sample.names = "matched (r=2)" )+mytheme
den_m_pasture <- bal.plot(baltest_covs2, treat = matched_wide_2$treat, var.name = "pasture", sample.names = "matched (r=2)" )+mytheme
den_m_road <- bal.plot(baltest_covs2, treat = matched_wide_2$treat, var.name = "road_dist", sample.names = "matched (r=2)" )+xlab("distance to road")+mytheme
den_m_slope <- bal.plot(baltest_covs2, treat = matched_wide_2$treat, var.name = "slope", sample.names = "matched (r=2)" )+mytheme
den_m_elev <- bal.plot(baltest_covs2, treat = matched_wide_2$treat, var.name = "elev", sample.names = "matched (r=2)" )+xlab("elevation")+mytheme
den_m_ndvi <- bal.plot(baltest_covs2, treat = matched_wide_2$treat, var.name = "y_2007", sample.names = "matched (r=2)" )+xlab("2007 NDVI")+bottom_theme+scale_fill_discrete( labels = c("non-enrollees", "enrollees"))

# density plots for unmatched data
den_un_plantation <- bal.plot(baltestun_covs, treat = df$treat, var.name = "plantation", sample.names = "unmatched" )+mytheme
den_un_forest <- bal.plot(baltestun_covs, treat = df$treat, var.name = "forest", sample.names = "unmatched" )+mytheme
den_un_pasture <- bal.plot(baltestun_covs, treat = df$treat, var.name = "pasture", sample.names = "unmatched" )+mytheme
den_un_road <- bal.plot(baltestun_covs, treat = df$treat, var.name = "road_dist", sample.names = "unmatched" )+xlab("distance to road")+mytheme
den_un_slope <- bal.plot(baltestun_covs, treat = df$treat, var.name = "slope", sample.names = "unmatched")+mytheme
den_un_elev <- bal.plot(baltestun_covs, treat = df$treat, var.name = "elev", sample.names = "unmatched" )+xlab("elevationI")+mytheme
den_un_ndvi <- bal.plot(baltestun_covs, treat = df$treat, var.name = "y_2007", sample.names = "unmatched" )+xlab("2007 NDVI")+bottom_theme+scale_fill_discrete( labels = c("non-enrollees", "enrollees"))

blankPlot <- ggplot()+geom_blank(aes(1,1))+
  theme(
    plot.background = element_blank(), 
   panel.grid.major = element_blank(),
   panel.grid.minor = element_blank(), 
   panel.border = element_blank(),
   panel.background = element_blank(),
   axis.title.x = element_blank(),
   axis.title.y = element_blank(),
   axis.text.x = element_blank(), 
   axis.text.y = element_blank(),
   axis.ticks = element_blank(),
   axis.line = element_blank()
     )

library(gridExtra)
grid.arrange(den_un_plantation, den_m_plantation,
             den_un_forest, den_m_forest,
             den_un_pasture, den_m_pasture,
             den_un_road, den_m_road,
             den_un_slope, den_m_slope,
            # den_un_elev, den_m_elev,
             den_un_ndvi, den_m_ndvi,
             #plot_grid(grid.draw(legend), ncol=1),blankPlot,
             ncol=2, heights=c(9,9,9,9,9,13))

```

```{r paid only}
library(MatchIt)
# create matched dataframes

df_paid <- df %>%
  drop_na(elev, slope)%>%
  filter(rptpro_tiene_plan_saff != "No" |is.na(rptpro_tiene_plan_saff))
  

pmatched_2009 <- matchit(treat ~ trend0807 + trend0706 + trend0605 + y_2007 +
                          forest + plantation + baresoil + pasture + urban +water + slope + elev  + area_ha + road_dist, 
                   data = subset(df_paid, first.treat == 0 | first.treat == 2009),
                 method = "nearest", ratio = 2)

pmatched_2010 <- matchit(treat ~ trend0908 + trend0807 + trend0706 + trend0605 + y_2007+ 
                          forest + plantation + baresoil + pasture + urban +water+ slope + elev  + area_ha + road_dist, 
                   data = subset(df_paid, first.treat == 0 | first.treat == 2010),
                 method = "nearest", ratio = 2)

pmatched_2011 <- matchit(treat ~ trend1009 + trend0908 + trend0807 + trend0706 +trend0605 + y_2007 + 
                          forest + plantation + baresoil + pasture  + urban +water+ slope + elev  + area_ha + road_dist, 
                   data = subset(df_paid, first.treat == 0 | first.treat == 2011),
                 method = "nearest", ratio = 2)

pmatched_2012 <- matchit(treat ~ trend1110 + trend1009 + trend0908 + trend0807+ trend0706 + y_2007 + 
                          forest + plantation + baresoil + pasture  + urban +water+ slope + elev  + area_ha + road_dist, 
                   data = subset(df_paid, first.treat == 0 | first.treat == 2012),
                 method = "nearest", ratio = 2)

pmatched_2013 <- matchit(treat ~ trend1211 + trend1110 + trend1009 + trend0908 +trend0807+ y_2007+ 
                          forest + plantation + baresoil + pasture + urban +water+ slope + elev  + area_ha + road_dist, 
                   data = subset(df_paid, first.treat == 0 | first.treat == 2013),
                 method = "nearest", ratio = 2)

pmatched_2014 <- matchit(treat ~ trend1312 + trend1211 + trend1110 + trend1009 + trend0908+ y_2007 + 
                          forest + plantation + baresoil + pasture + urban +water+ slope + elev  + area_ha + road_dist, 
                   data = subset(df_paid, first.treat == 0 | first.treat == 2014),
                 method = "nearest", ratio = 2)

pmatched_2015 <- matchit(treat ~ trend1413 + trend1312 + trend1211 + trend1110 + trend1009 + y_2007+ 
                          forest + plantation + baresoil + pasture  + urban +water+ slope + elev  + area_ha + road_dist, 
                   data = subset(df_paid, first.treat == 0 | first.treat == 2015),
                 method = "nearest", ratio = 2)

pmatched_2016 <- matchit(treat ~ trend1514 + trend1413 + trend1312 + trend1211 + trend1110+  y_2007+ 
                          forest + plantation + baresoil + pasture +urban +water+ slope + elev  + area_ha + road_dist, 
                   data = subset(df_paid, first.treat == 0 | first.treat == 2016),
                 method = "nearest", ratio = 2)

pmatched_2017 <- matchit(treat ~ trend1615 + trend1514 + trend1413 + trend1312 + trend1211+  y_2007+ 
                          forest + plantation + baresoil + pasture + urban +water+ slope + elev  + area_ha + road_dist, 
                   data = subset(df_paid, first.treat == 0 | first.treat == 2017),
                 method = "nearest", ratio = 2)

pmatched_2018 <- matchit(treat ~ trend1716 + trend1615 + trend1514 + trend1413 + trend1312 +  y_2007+ 
                          forest + plantation + baresoil + pasture + urban +water+ slope + elev  + area_ha + road_dist, 
                   data = subset(df_paid, first.treat == 0 | first.treat == 2018),
                 method = "nearest", ratio = 2)

pmatched_2019 <- matchit(treat ~ trend1817 + trend1716 + trend1615 + trend1514 + trend1413 + y_2007+ 
                          forest + plantation + baresoil + pasture+ urban +water+ slope + elev  + area_ha + road_dist, 
                   data = subset(df_paid, first.treat == 0 | first.treat == 2019),
                 method = "nearest", ratio = 2)

map_covars <- function(df){
  return_df <- df %>%
    group_by(subclass)%>%
    mutate(smallholder = max(smallholder, na.rm = TRUE),
         reforestation = max(reforestation, na.rm = TRUE),
         reforestation2 = max(reforestation2, na.rm = TRUE),
         area_prop = max(area_prop, na.rm = TRUE),
         did_group = max(first.treat, na.rm = TRUE)
         )%>%
    ungroup()
 return(return_df)
}

# group by matched pairs
pmatched_wide <- map_covars(match.data(pmatched_2009, subclass = "subclass"))%>%
  bind_rows(map_covars(match.data(pmatched_2010, subclass = "subclass")))%>%
  bind_rows(map_covars(match.data(pmatched_2011, subclass = "subclass")))%>%
  bind_rows(map_covars(match.data(pmatched_2012, subclass = "subclass")))%>%
  bind_rows(map_covars(match.data(pmatched_2013, subclass = "subclass")))%>%
  bind_rows(map_covars(match.data(pmatched_2014, subclass = "subclass")))%>%
  bind_rows(map_covars(match.data(pmatched_2015, subclass = "subclass")))%>%
  bind_rows(map_covars(match.data(pmatched_2016, subclass = "subclass")))%>%
  bind_rows(map_covars(match.data(pmatched_2017, subclass = "subclass")))%>%
  bind_rows(map_covars(match.data(pmatched_2018, subclass = "subclass")))%>%
  bind_rows(map_covars(match.data(pmatched_2019, subclass = "subclass")))%>%
  mutate(id = 1:nrow(.))

pbaltest_covs <- subset(pmatched_wide, select = c("forest" ,"plantation" , "baresoil", "pasture", "urban", "water", "slope", "elev", "area_ha", "road_dist"))

bal.tab(baltest_covs, treat = pmatched_wide$treat,thresholds = c(m = .25))

pmatched_long <- gather(pmatched_wide, "Year", "NDVI", y_2005:y_2020)%>%
  separate(Year, , into = c(NA, "Year"), sep = "_")

pmatched_long$Year <- as.numeric(pmatched_long$Year)
pmatched_long$id <- as.numeric(pmatched_long$id)

export(pmatched_long, "paid_analysis.rds")


```

