---
title: The carbon and land use impacts of Chilean payments for native reforestation
author: "Alberto Garcia"
date: "December 10, 2020"
output:
  pdf_document:
    latex_engine: xelatex
    number_sections: yes
    toc: yes
  html_document: default
  documentclass: article
#bibliography: chile_reforestation.bib
header-includes: 
  \usepackage{bbm}  
  \usepackage{graphicx}
  \usepackage{amsmath}
  \usepackage{amssymb}
  \usepackage{sectsty}
---

\sectionfont{\fontsize{11}{11}\selectfont}
\subsectionfont{\fontsize{11}{11}\selectfont}

```{r setup, include=FALSE}
library(knitr)
library(ggplot2)
library(kableExtra)
library(tidyverse)



knitr::opts_chunk$set(echo = TRUE)
```

\section{Motivation}  


There is room for an additional 0.9 billion hectares of canopy cover on earth, making reforestation one of the most viable carbon removal solutions (Bastin et al. 2019). Estimates reveal that reforestation may provide large scale carbon removals at a relatively low carbon price, and further, that reforestation offers more low-cost abatement than avoided deforestation in many countries (Busch et al. 2019).  Countries are expected to scale up restoration in an effort to meet global carbon and ecosystem restoration commitments, and payments for reforestation have the potential to help countries achieve these targets (Gichuki et al. 2019). 

Payments for reforestation fall under the broader category of payments for ecosystem services (PES), which offer payments to landowners in exchange for providing ecosystem or environmental services and have become the center of academic debate (Boerner et al. 2017). There exists rigorous empirical evidence surrounding the effectiveness of payments for avoided deforestation in the context of both randomized control trials (eg. Jayachandran et al. 2019) and quasi-experimental settings (eg. Arriagada et al. 2012), however, the number of studies evaluating the effectiveness of payments for afforestation and reforestation is quite small (Alix-Garcia and Wolff 2014). By offering a set payment for tree planting, landowners who can afforest or reforest below the offered subsidy price have an incentive to enroll in the program, whereas those with a higher opportunity cost will not enroll. 

The emerging market for carbon sequestration has sometimes encouraged afforestation and reforestation based on large scale forestry schemes in an effort to maximize tree planting and biomass production (IUCN 2016). This often incentivizes the use of fast growing non-native species and afforestation on native non-forest habitats. The regular clearing and harvesting of plantations may lead to accelerated soil degradation, an in turn, sabotage carbon storage potentials (eg. Chen et al. 2016). These schemes may also change the relative profitability of certain activities and generate unintended environmental consequences (Jack 2013), such as the conversion of natural forest or other native ecosystem types into plantation forest (Heilmayr et al. 2020). Concerns over this and other unintended consequences such as leakage (eg. Jack et al. 2008) and exacerbated distributional issues (eg. Wunder 2008) have led to the promotion of social and environmental safeguards that seek to mitigate negative impacts. These safeguards include the participation of indigenous peoples and smallholders, conservation of natural forests and biodiversity, and actions to reduce the risk of displaced emissions (United Nations n.d.).

The additional conservation benefits provided by the program relative to a ``No PES" scenario (ie. additionality) is determined by who participates and may be undermined when payments are made to landowners who would have undertaken conservation activities even in the absence of the program. Many factors further affect enrollment decisions that may ultimately affect the program’s cost-effectiveness and environmental benefits including application complexity, credit constraints, or the cost of obtaining information (Jack and Jayachandran 2018).

This paper will explore the social and environmental tradeoffs associated with Chile’s Decree Law no. 20.283 (Native Forest Law). The Native Forest Law came partly as a response to Decree Law no. 701, which prioritized the expansion of Chile's forestry sector, offering large afforestation subsidies for mostly non-native species of eucalyptus and pine. The Native Forest Law has incentivized native forest recovery and the participation of smallholders and indigenous peoples. With intensive tree plantations and natural forest regeneration after decades of forest destruction, We will examine the impacts of Chile's Native Forest Law and quantify its effectiveness in achieving a number of objectives, including vegetation cover, carbon sequestration, and attainment of social and environmental safeguards. 

\section{Chile's forest history and the Native Forest Law}

Chile’s forest incentives have served as a model for national forestry policy throughout much of Latin America [53, 54], howvwever, surprisingly little research has been conducted to assess the causal impacts of its policies. In effect between 1974 and 2012, Decree Law no. 701 (DL701) sought to encourage the growth of Chile’s forestry sector by reimbursing landowners for up to 90% of the cost of afforestation and forest management activities. In aggregate, the program paid $562 million to afforest 1.58 million hectares, the overwhelming majority of which supported the establishment of even-aged monocultures of exotic pines and eucalyptus [52]. Simulations indicate that the majority of subsidized plantations would likely have been established without subsidy payments, calling into question the additional impact of subsidy payments [44, 56]. Further, by increasing returns to plantation forestry, DL701 subsidies increased plantation expansion into native forests, shrub and agricultural lands [@Heilmayr2020]. In an attempt to encourage more reforestation of native forests, Chile passed the Ley de Recuperación del Bosque Nativo y Fomento Forestal (Native Forest Law) in 2008. 

In addition to protections for native forests, the law established an annual competition for grants to support private landowners in their efforts to restore or reforest their land using native species. Since 2009, more than $58 million have been allocated through these competitions to reforest 235 thousand hectares, with a particular emphasis placed upon supporting smallholders, indigenous peoples, and women. Landowners are able to claim larger subsidies for species that are endangered and in regions or ecosystems in more urgent need of native forest restoration. To our knowledge, no research has examined the causal impacts of the Native Forest Law. 

The annual contest under the Native Forest Law is broken into two broad categories: "smallholders" and "other interested parties". Landowners submit a management plan to be scored by a team of judges according to a pre-determined set of criteria that take into consideration the forest type, the specific activities being performed, whether the property is part of indegenous lands, and other property characteristics. Awards are distributed in the order of highest score until funds run out, starting with the smallholder contest and subsequently moving to other interested parties. After a property is awarded under the contest, a third party report is completed (within one to two years) to verify that the activity has been performed. The landowner is then paid in accordance with their award. 

\section{Data}
\subsection{Native Forest Law data}

Data on the Native Forest Law include information from each of the grant competitions conducted between 2009 and 2019. The associated data include each property’s coordinates, application scores, grant amount requested, proposed activities, description of forest type, the types of species that will be managed, as well as the name, gender and race of the applicant. We have access to all data on successful applications, and additional information on rejected applications. 

\subsection{Property boundaries}

Most of the administrative data outlined above only includes a single set of geospatial coordinates for each subsidy recipient or applicant. However, our spatial analysis of policy impacts necessitates detailed information on the footprint of the entire property that was subsidized. To fill this gap, we have acquired access to a database of the official boundaries of all rural properties in Chile. The date of these maps last updating ranges from 2013 to 2017 depending on region. This database links the boundaries of each property with the name and official parcel identifier for each property, as registered with Chile’s Internal Revenue Service. This information enables us to match program participants with their property's corresponding boundaries using the official parcel identifier. 

\subsection{Satellite data}

Two satellite derived measures of the subsidies' impacts will be used. First, we use NDVI to assess the subsidies' effect on vegetation cover on awarded properties. NDVI time series for each property from 2006 to 2018 are generated using the following procedure: 
\begin{enumerate}
\item compute NDVI for each Landsat 30m pixel that falls within a relevant property between the years 2007 and 2018
\item for each year, select each pixel's maximum NDVI value. 
\item compute the mean to get the property's annual NDVI value
\end{enumerate}
This process is based on Chen et al. (2019), who estimate the planting year of tree crops based on Landsat annual mean maximum NDVI time series. We use NDVI instead of the more popular Hansen et al. (2013) global forest cover data for several reasons. The dataset does not allow for forest gain to be detected on an annual level. Further, a binary value of forest gain is determined by a canopy cover threshold, which ignores the regrowth process of forest until it has reached the threshold value. This diminishes the ability to look at forest generation through time using the Hansen product. NDVI is a commonly used index to gauge forest cover and productivity. Trends in NDVI can be interpreted as measures of boreal forest productivity and act as an indication of tree growth and changes in forest composition (Beck et al. 2011). 

Future iterations of this paper will use annual maps of carbon stored in aboveground biomass, which are in the process of being generated. 

\section{Summary measures}
comparing smallholders vs. other interested parties:
- property characteristics: size, forest type
- award characteristics: money, ha subsidized, money per hectare
- owner characteristics: race, gender

anticipation: 
-2019 cohort: have they applied before? 
-rejected applicants: did they apply again?
-amongst rejected applicants who later received an award: did they change their application?

\section{Methods}

We use an event study design in order to assess the impacts of the subsidies on vegetation cover on awarded properties. The power of our research design is that it controls for observable time-varying covariates, as well as observable and unobservable, time-invariant confounders that might bias estimates of the causal effect of forest payments [20, 73]. As a result, the research design brings us closer to understanding the causal effect of reforestation payments on vegetation cover and the amount of carbon stored in aboveground biomass. This model requires the “common trends assumption” which implies that, in the absence of subsidy payments, enrolled and unenrolled properties would have experienced similar trends in carbon sequestration. This assumption could be violated if unobservable, time-varying determinants of carbon storage on a property (e.g., the property owner’s anticipation of future land use, their experience with forestry) are correlated with receipt of subsidy payments.

Recent research has shown that the canonical TWFE and corresponding event study regressions may return biased treatment effect estimates. For example, @borysyak2017, @goodman-bacon2018, and @dechaisemartin2020 show that these methods recover a weighted average of underlying treatment effect parameters, but some of the weights on these parameters can be negative. Given that our data include ten different cohorts of subsidy recipients and over 10 years of data, there is ample room for heterogeneity in treatment effects across groups and time-periods. In order to mitigate these concerns, I use the dynamic difference-in-differences estimator proposed by Callaway and Santa'ana (2019). Our method first calculates a generalized propensity score to better compare treatment and control units based on a detailed set of covariates. Then, for each cohort and time period, I compute the standard DID, using the propensity score weights. The group-time treatment effects are then aggregated with weights corresponding to each group's sample representativeness. This ensures that the weights for each group-time treatment effect are not negative, and therefore, do not risk reversing the sign of the treatment effect estimate. Unlike the standard TWFE event study, this method provides an unbiased and consistent estimate of the dynamic treatment effect in the presence of treatment effect heterogeneity. 

The dynamic treatment effect estimates I present are described by the expression below, where $e$ denotes the time elapsed since treatment was adopted. 

$$ \theta_{es}(e) = \sum_{g \in G}1\{ g+e \leq T \} P(G=g|G+e\leq T) ATT(g, g+e)$$

This is the average effect of participating in the treatment $e$ time periods after the treatment was adopted across all groups that are ever observed to have participated in the treatment for e time periods. All weights $P(G=g|G+e\leq T)$ are nonnegative and sum to one. Here, we note that 

$$  ATT(g, g+e) = \mathbb{E}[Y_{g+e}(g) - Y_{g+e}(0) | G_g = 1]$$,

which represents the average treatment effect for group $g$, in time period $g+e$ (i.e. $e$ periods after treatment). 

\section{Results}

\section{Robustness}

\subsection{to anticipation}

\subsection{incorporating intensity of treatment}