---
title: "building native forest law impact dataframes"
#author: "Albert Garcia"
output:
  pdf_document:
    number_sections: yes
    toc: no
fontsize: 11pt    
documentclass: article
geometry: margin=1in
header-includes: 
  \usepackage{sectsty}
  \usepackage{enumitem}
  \usepackage{comment}
  \usepackage{multirow,array}
  \usepackage{makecell}
  \usepackage{dcolumn}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(out.height='300px', dpi=200)

### loads tidyverse packages, defines helper functions
library(latex2exp)
library(tidyverse)
library(ggplot2)
library(readxl)
library(sf)
library(stringi)
library(data.table)
library(fuzzyjoin)
library(stringdist)

```

```{r}
setwd("C:/Users/garci/Dropbox/chile_reforestation/external_data")

# xls files downloaded from CONAF
#projects
payments_df <- read.csv("concurso_conaf/beneficiarios.csv", header=T)

## define a helper function
empty_as_na <- function(x){
    if("factor" %in% class(x)) x <- as.character(x) ## since ifelse wont work with factors
    ifelse(as.character(x)!="", x, NA)
}

accents <- function(x){
  x <- stri_trans_general(x, id = "Latin-ASCII")
}

## transform all columns
payments_df <- payments_df %>% 
  mutate_each(funs(empty_as_na))%>%
  rename(rptprop_apellido_paterno = Apellido.paterno.del.beneficiario,
         rptprop_apellido_materno = Apellido.materno.del.beneficiario,
         rptprop_razon_social = Razón.Social..si.receptor.es.persona.jurídica)%>%
  mutate(apellido_ID = group_indices(., rptprop_apellido_paterno, rptprop_apellido_materno),
         unique_ID = group_indices(., rptprop_apellido_paterno, rptprop_apellido_materno, Nombres.del.beneficiario))%>%
  mutate_at(c("rptprop_apellido_paterno", "rptprop_apellido_materno", "rptprop_razon_social", "Nombres.del.beneficiario"), accents)%>%
  mutate_at(c("rptprop_apellido_paterno", "rptprop_apellido_materno", "rptprop_razon_social", "Nombres.del.beneficiario"), tolower)

rolarea_df <- property_df %>%
  #mutate_each(funs(empty_as_na))%>%
  mutate_at(c("rptprop_apellido_paterno", "rptprop_apellido_materno", "rptprop_razon_social", "rptprop_nombre"), accents)%>%
  mutate_at(c("rptprop_apellido_paterno", "rptprop_apellido_materno", "rptprop_razon_social", "rptprop_nombre"), tolower)%>%
  unite(apellidos, c(rptprop_apellido_paterno, rptprop_apellido_materno), sep = " ", remove = FALSE)

rolarea_df$rptprop_razon_social[is.na(rolarea_df$rptprop_razon_social)] <- "empty_string"
  
ind_payments <- payments_df %>%
  drop_na(rptprop_apellido_paterno) %>%
    unite(apellidos, c(rptprop_apellido_paterno, rptprop_apellido_materno), sep = " ", remove = FALSE)%>%
    stringdist_inner_join(rolarea_df, by = c("apellidos"), max_dist = 1)%>%
  #select(prop_ID, apellidos.x , apellidos.y, rptprop_nombre, Nombres.del.beneficiario)%>%
  separate(rptprop_nombre, c("a", "b", "c", "d"), remove = FALSE) %>%
  separate(Nombres.del.beneficiario, c("A", "B", "C", "D"), remove = FALSE) %>%
  mutate(stringaa = stringdist(a, A, method = "dl"), 
         stringab = stringdist(a, B, method = "dl"),
         stringac = stringdist(a, C, method = "dl"),
         stringad = stringdist(a, D, method = "dl"),
         stringba = stringdist(b, A, method = "dl"),
         stringbb = stringdist(b, B, method = "dl"),
         stringbc = stringdist(b, C, method = "dl"),
         stringbd = stringdist(b, D, method = "dl"),
         stringca = stringdist(c, A, method = "dl"),
         stringcb = stringdist(c, B, method = "dl"),
         stringcc = stringdist(c, C, method = "dl"),
         stringcd = stringdist(c, D, method = "dl"),
         stringda = stringdist(d, A, method = "dl"),
         stringdb = stringdist(d, B, method = "dl"),
         stringdc = stringdist(d, C, method = "dl"),
         stringdd = stringdist(d, D, method = "dl")
         )

ind_payments$meets_string1 <- rowSums( ind_payments[,startsWith(names(ind_payments),"string")] <= 1
    , na.rm = TRUE) >= 1

ind_paid <- ind_payments %>%
  filter(meets_string1 == "TRUE")%>%
  #select(prop_ID, apellidos.x , apellidos.y, rptprop_nombre, Nombres.del.beneficiario)%>%
  group_by(prop_ID)%>%
  mutate(namestringd = stringdist(rptprop_nombre, Nombres.del.beneficiario, method = "dl"),
         name_ranks = order(order(namestringd, decreasing=FALSE))
         )%>%
  ungroup()%>%
  filter(name_ranks ==1)

social_payments <- payments_df %>%
  drop_na(rptprop_razon_social) %>%
    stringdist_inner_join(rolarea_df, by = c("rptprop_razon_social"), max_dist = 20)%>%
  #select(prop_ID, rptprop_razon_social.x, rptprop_razon_social.y)%>%
  separate(rptprop_razon_social.x, c("a", "b", "c", "d", "e", "f"), remove = FALSE) %>%
  separate(rptprop_razon_social.y, c("A", "B", "C", "D", "E", "F"), remove = FALSE) %>%
  mutate(stringaa = stringdist(a, A, method = "dl"), 
         stringab = stringdist(a, B, method = "dl"),
         stringac = stringdist(a, C, method = "dl"),
         stringad = stringdist(a, D, method = "dl"),
         stringae = stringdist(a, E, method = "dl"),
         stringaf = stringdist(a, F, method = "dl"),
         stringba = stringdist(b, A, method = "dl"),
         stringbb = stringdist(b, B, method = "dl"),
         stringbc = stringdist(b, C, method = "dl"),
         stringbd = stringdist(b, D, method = "dl"),
         stringbe = stringdist(b, E, method = "dl"),
         stringbf = stringdist(b, F, method = "dl"),
         stringca = stringdist(c, A, method = "dl"),
         stringcb = stringdist(c, B, method = "dl"),
         stringcc = stringdist(c, C, method = "dl"),
         stringcd = stringdist(c, D, method = "dl"),
         stringce = stringdist(c, E, method = "dl"),
         stringcf = stringdist(c, F, method = "dl"),
         stringda = stringdist(d, A, method = "dl"),
         stringdb = stringdist(d, B, method = "dl"),
         stringdc = stringdist(d, C, method = "dl"),
         stringdd = stringdist(d, D, method = "dl"),
         stringde = stringdist(d, E, method = "dl"),
         stringdf = stringdist(d, F, method = "dl"),
         stringea = stringdist(e, A, method = "dl"), 
         stringeb = stringdist(e, B, method = "dl"),
         stringec = stringdist(e, C, method = "dl"),
         stringed = stringdist(e, D, method = "dl"),
         stringee = stringdist(e, E, method = "dl"),
         stringef = stringdist(e, F, method = "dl"),
         stringfa = stringdist(f, A, method = "dl"), 
         stringfb = stringdist(f, B, method = "dl"),
         stringfc = stringdist(f, C, method = "dl"),
         stringfd = stringdist(f, D, method = "dl"),
         stringfe = stringdist(f, E, method = "dl"),
         stringff = stringdist(f, F, method = "dl")
         )

social_payments$meets_string2 <- rowSums( social_payments[,startsWith(names(social_payments),"string")] == 0
    , na.rm = TRUE) >= 2

social_payments$meets_string3 <- rowSums( social_payments[,startsWith(names(social_payments),"string")] <= 1
    , na.rm = TRUE) >= 3

social_payments$meets_string4 <- rowSums( social_payments[,startsWith(names(social_payments),"string")] <= 1
    , na.rm = TRUE) >= 4

soc_paid <- social_payments %>%
  #select(prop_ID, rptprop_razon_social.x, rptprop_razon_social.y)%>%
  mutate(namestringd = stringdist(rptprop_razon_social.x, rptprop_razon_social.y))%>%
  group_by(prop_ID)%>%
  mutate(namestringd = stringdist(rptprop_razon_social.x, rptprop_razon_social.y, method = "dl"),
         name_ranks = order(order(namestringd, decreasing=FALSE))
         )%>%
  ungroup()%>%
  filter(name_ranks ==1 & (
    (meets_string4 == "TRUE" & namestringd <= 5)|
      (meets_string3 == "TRUE" & namestringd <= 4)|
      (meets_string2 == "TRUE" & namestringd <= 3)|
      namestringd <= 1 )
  )

check_paid <- soc_paid %>%
  bind_rows(ind_paid) %>%
  select(prop_ID, apellidos.x, apellidos.y, rptprop_razon_social.x, rptprop_razon_social.y, rptprop_nombre, Nombres.del.beneficiario, rptpro_ano, name_ranks, Acto.por.el.cual.se.otorgó, namestringd, meets_string1, meets_string2, meets_string3, meets_string4)

paid_ids <- check_paid %>%
  select(prop_ID)%>%
  mutate(paid = 1)

length(unique(payments_df$unique_ID))/length(unique(property_df$prop_ID))#0.4496585
length(unique(check_paid$prop_ID))/length(unique(rolarea_df$prop_ID))
#0.3845561 rolarea
# 0.385217 property (full)
  
```

