---
title: "intensity analysis"
#author: "Albert Garcia"
output:
  pdf_document:
    number_sections: yes
    toc: no
fontsize: 11pt    
documentclass: article
geometry: margin=1in
header-includes: 
  \usepackage{sectsty}
  \usepackage{enumitem}
  \usepackage{comment}
  \usepackage{multirow,array}
  \usepackage{makecell}
  \usepackage{dcolumn}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(out.height='300px', dpi=200)

### loads tidyverse packages, defines helper functions
library(latex2exp)
library(tinytex)
library(tidyverse)
library(ggplot2)
library(readxl)
library(sf)
library(stringi)
library(data.table)
library(kableExtra)
library(stringdist)
library(GADMTools)
library(rnaturalearth)
#library(reshape2)

library(did)
library(AER)
library(dynlm)
library(plm)
library(stargazer)
library(Metrics)
library(DataCombine)
library(Hmisc)

```

``` {r NFL_data, echo = FALSE, message = FALSE, warning = FALSE, include = FALSE, eval = TRUE}
#setting working directory

setwd("C:/Users/garci/Desktop/chile_data/nativeforestlaw")

# xls files downloaded from CONAF
#projects
proyecto_1 <- read_excel("proyectos_1.xls")
proyecto_2 <- read_excel("proyectos_2.xls")
proyecto_df <- merge(proyecto_1, proyecto_2, by = c("rptpro_id", "rptpro_numero_ingreso"), all=TRUE)
#properties and coordinates
predio_df <- read_excel("predio.xls")
coordinadas_predio_df <- read_excel("coordinadas_predio.xls")
#owners
propietario_df <- read_excel("propietario.xls")
#stands
rodal_1 <- read_excel("rodal_1.xls")
rodal_2 <- read_excel("rodal_2.xls")
rodal_df <- merge(rodal_1, rodal_2, by = c("rptro_id"), all=TRUE)
#activities
actividades_1 <- read_excel("actividades_1.xls")
actividades_2 <- read_excel("actividades_2.xls")
actividades_df <- merge(actividades_1, actividades_2, by = c("rptac_id"), all=TRUE)
#fences
cercos_df <- read_excel("cerco.xls")

#merging into dataframe of all properties and owners
property_df <- proyecto_df %>%
  left_join(predio_df, by = c("rptpro_id", "rptpro_numero_ingreso")) %>%
  left_join(propietario_df, by = "rptpre_id")

#merging into full data set
NFL_df <- proyecto_df %>%
  left_join(predio_df, by = c("rptpro_id", "rptpro_numero_ingreso")) %>%
  left_join(propietario_df, by = "rptpre_id") %>%
  left_join(coordinadas_predio_df, by = "rptpre_id") %>%
  left_join(rodal_df, by = "rptpre_id") %>%
  left_join(actividades_df, by = "rptro_id") 

covars <- property_df %>%
  select(rptpro_ano, rptpre_rol, rptpre_comuna, rptpre_region, rptpro_tipo_concurso, rptpro_objetivo_manejo, rptpro_monto_total, rptpro_puntaje, rptpre_superficie_predial, rptpre_superficie_bonificada)%>%
  rename(ROL = rptpre_rol)%>%
  distinct(ROL, rptpre_comuna, rptpro_ano,  .keep_all = TRUE)

activity_df <- NFL_df %>%
  dcast(rptpre_rol + rptpre_comuna + rptpro_ano
        ~ rptac_tipo, 
        fun.aggregate = function(x){as.integer(length(x) > 0)})

CIREN_list <- NFL_df %>%
  select(rptpre_rol, rptpre_comuna) %>%
  distinct() %>%
  rename(ROL = rptpre_rol,
         COMUNA = rptpre_comuna)%>%
  filter(ROL != "-" )

#write.csv(CIREN_list, file = "CIREN_list.csv", row.names = FALSE)

```

```{r CIREN_data, echo = FALSE, message = FALSE, warning = FALSE, include = FALSE, eval = TRUE}
#uploading rural property cadastre shapefile
prop_rural.shp <- st_read(
  "C:/Users/garci/Desktop/chile_data/prop_rural/prop_rural.shp"
  )
# creating simple features object with rural properties shapefile
prop_rural.sf <- st_as_sf(prop_rural.shp) %>%
  st_transform("+proj=longlat +datum=WGS84")#transform crs

prop_rural.sf$DESCCOMU <- as.character(prop_rural.sf$DESCCOMU)

```

```{r CIREN_data, echo = FALSE, message = FALSE, warning = FALSE, include = FALSE, eval = TRUE}
  
rol_df <- activity_df %>%
  rename(ROL = rptpre_rol) %>% #renaming rols to be the same in both datasets
  inner_join(prop_rural.sf, by = "ROL") %>%
  mutate(comuna_stringd = stringdist(rptpre_comuna, DESCCOMU, method = "dl")) %>%
  filter(comuna_stringd <= 1) %>%
  mutate(ID = group_indices(., ROL, rptpre_comuna))

rol_distinct <- rol_df %>%
  st_sf(sf_column_name = "geometry", crs = "+proj=longlat +datum=WGS84") %>%
  select(ID) %>%
  distinct()

id_distinct <- rol_df %>%
  distinct(ID, .keep_all = TRUE) %>%
  st_sf(sf_column_name = "geometry", crs = "+proj=longlat +datum=WGS84") %>%
  select(ID) 


# # reforestation: plantacion, plantacion-supplementaria, regeneracion
# reforestation_rols <- rol_df %>%
#   filter(plantacion == 1 | `plantacion-suplementaria` ==1 | regeneracion ==1) %>%
#   select(ID) %>%
#   distinct()
  # reforestation_geoms <- reforestation_rols %>%
  # left_join(geoms, by = "ID")

```


```{r data frame for estimation, echo = FALSE, message = FALSE, warning = FALSE, include = FALSE, eval = TRUE}
  
nativeforestlaw_df <- rol_df %>%
  group_by(ID) %>%
  mutate(first.treat = min(rptpro_ano),
         latest.treat = max(rptpro_ano))%>%
  filter(rptpro_ano == first.treat) %>%
  ungroup() %>%
  mutate(treated.later = ifelse( first.treat != latest.treat, 1, 0)) %>%
  distinct(ID, .keep_all = TRUE) %>%
  st_sf(sf_column_name = "geometry", crs = "+proj=longlat +datum=WGS84") %>%
  st_centroid()%>%
    mutate(lat = unlist(map(nativeforestlaw_df$geometry,1)),
           long = unlist(map(nativeforestlaw_df$geometry,2))) 

#table(nativeforestlaw_df$treated.later)

```

```{r geoms, echo = FALSE, message = FALSE, warning = FALSE, include = FALSE, eval = TRUE}

#st_write(id_distinct[1:2,], dsn = "test1.json", driver = "GeoJSON")

# id_poly_a <- paste0(id_distinct$ID[1:75], collapse=",")
# write.csv(id_poly_a, file = "id_poly_1.txt", row.names = FALSE)
# st_write(id_distinct[1:75,], dsn = "id_poly_a.json", driver = "GeoJSON")

# id_poly_b <- paste0(id_distinct$ID[76:150], collapse=",")
# write.csv(id_poly_b, file = "id_poly_b.txt", row.names = FALSE)
# st_write(id_distinct[76:150,], dsn = "id_poly_b.json", driver = "GeoJSON")

# id_poly_c <- paste0(id_distinct$ID[151:200], collapse=",")
# write.csv(id_poly_c, file = "id_poly_c.txt", row.names = FALSE)
# st_write(id_distinct[151:200,], dsn = "id_poly_c.json", driver = "GeoJSON")

# id_poly_d <- paste0(id_distinct$ID[201:275], collapse=",")
# write.csv(id_poly_d, file = "id_poly_d.txt", row.names = FALSE)
# st_write(id_distinct[201:275,], dsn = "id_poly_d.json", driver = "GeoJSON")

# id_poly_e <- paste0(id_distinct$ID[276:350], collapse=",")
# write.csv(id_poly_e, file = "id_poly_e.txt", row.names = FALSE)
# st_write(id_distinct[276:350,], dsn = "id_poly_e.json", driver = "GeoJSON")

# id_poly_f <- paste0(id_distinct$ID[351:425], collapse=",")
# write.csv(id_poly_f, file = "id_poly_f.txt", row.names = FALSE)
# st_write(id_distinct[351:425,], dsn = "id_poly_f.json", driver = "GeoJSON")

# id_poly_g <- paste0(id_distinct$ID[426:500], collapse=",")
# write.csv(id_poly_g, file = "id_poly_g.txt", row.names = FALSE)
# st_write(id_distinct[426:500,], dsn = "id_poly_g.json", driver = "GeoJSON")
# 
# id_poly_h <- paste0(id_distinct$ID[501:575], collapse=",")
# write.csv(id_poly_h, file = "id_poly_h.txt", row.names = FALSE)
# st_write(id_distinct[501:575,], dsn = "id_poly_h.json", driver = "GeoJSON")

# id_poly_i <- paste0(id_distinct$ID[576:650], collapse=",")
# write.csv(id_poly_i, file = "id_poly_i.txt", row.names = FALSE)
# st_write(id_distinct[576:650,], dsn = "id_poly_i.json", driver = "GeoJSON")

# id_poly_j <- paste0(id_distinct$ID[651:725], collapse=",")
# write.csv(id_poly_j, file = "id_poly_j.txt", row.names = FALSE)
# st_write(id_distinct[651:725,], dsn = "id_poly_j.json", driver = "GeoJSON")

# id_poly_k <- paste0(id_distinct$ID[726:800], collapse=",")
# write.csv(id_poly_k, file = "id_poly_k.txt", row.names = FALSE)
# st_write(id_distinct[726:800,], dsn = "id_poly_k.json", driver = "GeoJSON")

# id_poly_l <- paste0(id_distinct$ID[801:875], collapse=",")
# write.csv(id_poly_l, file = "id_poly_l.txt", row.names = FALSE)
# st_write(id_distinct[801:875,], dsn = "id_poly_l.json", driver = "GeoJSON")

# id_poly_m <- paste0(id_distinct$ID[876:950], collapse=",")
# write.csv(id_poly_m, file = "id_poly_m.txt", row.names = FALSE)
# st_write(id_distinct[876:950,], dsn = "id_poly_m.json", driver = "GeoJSON")

# id_poly_n <- paste0(id_distinct$ID[951:981], collapse=",")
# write.csv(id_poly_n, file = "id_poly_n.txt", row.names = FALSE)
# st_write(id_distinct[951:982,], dsn = "id_poly_n.json", driver = "GeoJSON")

# id_poly_o <- paste0(id_distinct$ID[983:1050], collapse=",")
# write.csv(id_poly_o, file = "id_poly_o.txt", row.names = FALSE)
# st_write(id_distinct[983:1050,], dsn = "id_poly_o.json", driver = "GeoJSON")

# id_poly_p <- paste0(id_distinct$ID[1051:1125], collapse=",")
# write.csv(id_poly_p, file = "id_poly_p.txt", row.names = FALSE)
# st_write(id_distinct[1051:1125,], dsn = "id_poly_p.json", driver = "GeoJSON")

# id_poly_q1 <- paste0(id_distinct$ID[1126:1132], collapse=",")
# write.csv(id_poly_q1, file = "id_poly_q1.txt", row.names = FALSE)
# st_write(id_distinct[1126:1132,], dsn = "id_poly_q1.json", driver = "GeoJSON")
# 
# id_poly_q2 <- paste0(id_distinct$ID[1134:1200], collapse=",")
# write.csv(id_poly_q2, file = "id_poly_q2.txt", row.names = FALSE)
# st_write(id_distinct[1134:1200,], dsn = "id_poly_q2.json", driver = "GeoJSON")

# id_poly_r <- paste0(id_distinct$ID[1201:1275], collapse=",")
# write.csv(id_poly_r, file = "id_poly_r.txt", row.names = FALSE)
# st_write(id_distinct[1201:1275,], dsn = "id_poly_r.json", driver = "GeoJSON")

# id_poly_s <- paste0(id_distinct$ID[1276:1350], collapse=",")
# write.csv(id_poly_s, file = "id_poly_s.txt", row.names = FALSE)
# st_write(id_distinct[1276:1350,], dsn = "id_poly_s.json", driver = "GeoJSON")

# id_poly_t <- paste0(id_distinct$ID[1276:1350], collapse=",")
# write.csv(id_poly_t, file = "id_poly_t.txt", row.names = FALSE)
# st_write(id_distinct[1276:1350,], dsn = "id_poly_t.json", driver = "GeoJSON")

# id_poly_u <- paste0(id_distinct$ID[1351:1425], collapse=",")
# write.csv(id_poly_u, file = "id_poly_u.txt", row.names = FALSE)
# st_write(id_distinct[1351:1425,], dsn = "id_poly_u.json", driver = "GeoJSON")
# 
# id_poly_v <- paste0(id_distinct$ID[1426:1500], collapse=",")
# write.csv(id_poly_v, file = "id_poly_v.txt", row.names = FALSE)
# st_write(id_distinct[1426:1500,], dsn = "id_poly_v.json", driver = "GeoJSON")

# id_poly_w <- paste0(id_distinct$ID[1501:1550], collapse=",")
# write.csv(id_poly_w, file = "id_poly_w.txt", row.names = FALSE)
# st_write(id_distinct[1501:1550,], dsn = "id_poly_w.json", driver = "GeoJSON")
# 
# id_poly_x <- paste0(id_distinct$ID[1552:1625], collapse=",")
# write.csv(id_poly_x, file = "id_poly_x.txt", row.names = FALSE)
# st_write(id_distinct[1552:1625,], dsn = "id_poly_x.json", driver = "GeoJSON")

# id_poly_y1 <- paste0(id_distinct$ID[1626:1631], collapse=",")
# write.csv(id_poly_y1, file = "id_poly_y1.txt", row.names = FALSE)
# st_write(id_distinct[1626:1631,], dsn = "id_poly_y1.json", driver = "GeoJSON")
# 
# id_poly_y2 <- paste0(id_distinct$ID[1634:1700], collapse=",")
# write.csv(id_poly_y2, file = "id_poly_y2.txt", row.names = FALSE)
# st_write(id_distinct[1634:1700,], dsn = "id_poly_y2.json", driver = "GeoJSON")

# id_poly_z <- paste0(id_distinct$ID[1701:1775], collapse=",")
# write.csv(id_poly_z, file = "id_poly_z.txt", row.names = FALSE)
# st_write(id_distinct[1701:1775,], dsn = "id_poly_z.json", driver = "GeoJSON")

# id_poly_aa <- paste0(id_distinct$ID[1776:1825], collapse=",")
# write.csv(id_poly_aa, file = "id_poly_aa.txt", row.names = FALSE)
# st_write(id_distinct[1776:1825,], dsn = "id_poly_aa.json", driver = "GeoJSON")

# id_poly_ab <- paste0(id_distinct$ID[1826:1900], collapse=",")
# write.csv(id_poly_ab, file = "id_poly_ab.txt", row.names = FALSE)
# st_write(id_distinct[1826:1900,], dsn = "id_poly_ab.json", driver = "GeoJSON")

# id_poly_ac <- paste0(id_distinct$ID[1901:1950], collapse=",")
# write.csv(id_poly_ac, file = "id_poly_ac.txt", row.names = FALSE)
# st_write(id_distinct[1901:1950,], dsn = "id_poly_ac.json", driver = "GeoJSON")

# id_poly_ad <- paste0(id_distinct$ID[1951:2000], collapse=",")
# write.csv(id_poly_ad, file = "id_poly_ad.txt", row.names = FALSE)
# st_write(id_distinct[1951:2000,], dsn = "id_poly_ad.json", driver = "GeoJSON")
# 
# id_poly_ae <- paste0(id_distinct$ID[2001:2075], collapse=",")
# write.csv(id_poly_ae, file = "id_poly_ae.txt", row.names = FALSE)
# st_write(id_distinct[2001:2075,], dsn = "id_poly_ae.json", driver = "GeoJSON")
# 
# id_poly_af <- paste0(id_distinct$ID[2076:2136], collapse=",")
# write.csv(id_poly_af, file = "id_poly_af.txt", row.names = FALSE)
# st_write(id_distinct[2076:2136,], dsn = "id_poly_af.json", driver = "GeoJSON")
# 
# id_poly_ag <- paste0(id_distinct$ID[2138:2200], collapse=",")
# write.csv(id_poly_ag, file = "id_poly_ag.txt", row.names = FALSE)
# st_write(id_distinct[2138:2200,], dsn = "id_poly_ag.json", driver = "GeoJSON")

```


``` {r awarded NDVI, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE, eval = TRUE}


#setting working directory

setwd("C:/Users/garci/Desktop/chile_data/ID_NDVI")

#upload and bind csvs together
awarded_ndvi <- 
  list.files(pattern = "*.csv") %>% 
  map_df(~read_csv(.)) %>%
  as.data.frame() %>% #turn into dataframe
  rename(ID = Code)



#match NDVIs with dataset
awarded_panel <- awarded_ndvi %>%
  inner_join(nativeforestlaw_df, by = "ID") %>% 
  inner_join(covars, by = c("rptpre_comuna", "ROL", "rptpro_ano"))%>%
  mutate(first.treat = ifelse(first.treat >=2019, 0, first.treat),
         treat = ifelse(first.treat >= 2019, 0, 1)
         ) 

awarded_panel$ID <- as.character(awarded_panel$ID)

```

``` {r awarded panel, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE, eval = TRUE}

# write_rds(
#   awarded_panel,
#   path = "awarded_panel.rds")
# #export(awarded_panel, "awarded_panel.rds")

```