---
title: "current progress for matching Native Forest Law enrolled properties to CIREN cadastre"
author: "Albert Garcia"
output:
  pdf_document:
    number_sections: yes
    toc: no
fontsize: 11pt    
documentclass: article
geometry: margin=1in
header-includes: 
  \usepackage{sectsty}
  \usepackage{enumitem}
  \usepackage{comment}
  \usepackage{multirow,array}
  \usepackage{makecell}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

### loads tidyverse packages, defines helper functions
library(latex2exp)
library(tinytex)
library(tidyverse)
library(ggplot2)
library(readxl)
library(sf)
library(stringi)
library(data.table)
library(kableExtra)
library(stringdist)

source('crs_clean_fcn.R')

```

``` {r NFL_data, echo = FALSE, message = FALSE, warning = FALSE, include = FALSE}
#setting working directory

setwd("C:/Users/garci/Desktop/chile_data/nativeforestlaw")

# xls files downloaded from CONAF
#projects
proyecto_1 <- read_excel("proyectos_1.xls")
proyecto_2 <- read_excel("proyectos_2.xls")
proyecto_df <- merge(proyecto_1, proyecto_2, by = c("rptpro_id", "rptpro_numero_ingreso"), all=TRUE)
#properties and coordinates
predio_df <- read_excel("predio.xls")
coordinadas_predio_df <- read_excel("coordinadas_predio.xls")
#owners
propietario_df <- read_excel("propietario.xls")
#stands
rodal_1 <- read_excel("rodal_1.xls")
rodal_2 <- read_excel("rodal_2.xls")
rodal_df <- merge(rodal_1, rodal_2, by = c("rptro_id"), all=TRUE)
#activities
actividades_1 <- read_excel("actividades_1.xls")
actividades_2 <- read_excel("actividades_2.xls")
actividades_df <- merge(actividades_1, actividades_2, by = c("rptac_id"), all=TRUE)
#fences
cercos_df <- read_excel("cerco.xls")

#merging into full data set
df_full <- proyecto_df %>%
  left_join(predio_df, by = c("rptpro_id", "rptpro_numero_ingreso")) %>%
  left_join(propietario_df, by = "rptpre_id") %>%
  left_join(coordinadas_predio_df, by = "rptpre_id") %>%
  left_join(rodal_df, by = "rptpre_id") %>%
  left_join(actividades_df, by = "rptro_id")


#northing easting huso datum
df_stand <- df_full %>%
  mutate(northing = 
           ifelse(is.na(rptro_norte), rptub_norte, rptro_norte)
         ) %>%
  mutate(easting = 
           ifelse(is.na(rptro_este), rptub_este, rptro_este)
         ) %>%
  mutate(datum = 
           ifelse(is.na(rptro_este) | is.na(rptro_norte), rptub_datum, rptro_datum)
         ) %>%
  mutate(huso = 
           ifelse(is.na(rptro_este) | is.na(rptro_norte), rptub_huso, rptro_huso)
         ) 

```


``` {r CIREN_data, echo = FALSE, message = FALSE, warning = FALSE, include = FALSE}
#uploading rural property cadastre shapefile
prop_rural.shp <- st_read(
  "C:/Users/garci/Desktop/chile_data/prop_rural/prop_rural.shp"
  )
# creating simple features object with rural properties shapefile
prop_rural.sf <- st_as_sf(prop_rural.shp) %>%
  st_transform(crs = "+proj=utm +zone=19 +south +ellps=aust_SA +units=m +no_defs")
```


``` {r updated CIREN_data, echo = FALSE, message = FALSE, warning = FALSE, include = FALSE}
#uploading rural property cadastre shapefile

reg3.shp<- st_read(
  "C:/Users/garci/Desktop/Roles_sad69_19s/III_REGION/rroles_3.shp"
  )

reg4.shp<- st_read(
  "C:/Users/garci/Desktop/Roles_sad69_19s/IV_REGION/region_4.shp"
  )

reg11.shp<- st_read(
  "C:/Users/garci/Desktop/Roles_sad69_19s/XI_REGION/region_11.shp"
  )

reg12.shp<- st_read(
  "C:/Users/garci/Desktop/Roles_sad69_19s/XII_REGION/PREDIOS-MARZO2007.shp"
  )

# creating simple features object with shapefile
reg3.sf <- st_as_sf(reg3.shp) %>%
  st_set_crs("+proj=utm +zone=19 +south +ellps=aust_SA +units=m +no_defs")
reg4.sf <- st_as_sf(reg4.shp) %>%
  st_set_crs("+proj=utm +zone=19 +south +ellps=aust_SA +units=m +no_defs")
reg11.sf <- st_as_sf(reg11.shp) %>%
  st_set_crs("+proj=utm +zone=19 +south +ellps=aust_SA +units=m +no_defs")
reg12.sf <- st_as_sf(reg12.shp) %>%
  st_set_crs("+proj=utm +zone=19 +south +ellps=aust_SA +units=m +no_defs")

# oth_regions.sf <- reg3.sf %>% 
#   st_join(reg4.sf, join = st_union) %>%
#   st_join(reg11.sf, join = st_union) %>%
#   st_join(reg12.sf, join = st_union)

```


# matching enrolled Native Forest Law properties to CIRN rural properties

## Native Forest Law property coordinates and projections


``` {r projection cleaning, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE, eval = TRUE}

#using crs_clean_fcn to use common projection
new_df.sf <- crs_clean_fcn(df_stand) #outputs sf df with common projection (sad69 zone 19s)

st_crs(new_df.sf)

```



## Spatially joining using the provided stand coordinates

``` {r spatial join, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE, eval = TRUE}

df_joined <- prop_rural.sf %>%
  st_join(new_df.sf, join = st_intersects) %>%
  drop_na(rptpro_id)

reg12_joined <- reg12.sf %>%
  st_join(new_df.sf, join = st_intersects) %>%
  drop_na(rptpro_id)

reg11_joined <- reg11.sf %>%
  st_join(new_df.sf, join = st_intersects) %>%
  drop_na(rptpro_id)

length(unique(df_joined$rptpre_rol))

#length(unique(df_joined[df_joined$rptpre_rol == df_joined$ROL,]$rptpro_id))

```



``` {r fuzzy scoring, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE, eval = TRUE}

# We will create columns with measures of how close the match was
# variables for matching score:
### if rol matches exactly
### if rol is similar (matches on first part)


#create variable with only first part of rol, separating by -


join_assess_df <- df_joined %>%
  select(rptpro_id, rptpre_region, ROL, rptpre_rol, NOM_PREDIO, rptpre_nombre) %>%
  separate(col = ROL, into = c("partial_rol_CIREN", NA), sep = "-", remove = FALSE) %>%
  separate(col = rptpre_rol, into = c("partial_rol_NFL", NA), sep = "-", remove = FALSE) %>%
  mutate(partial_rol_match = 
           ifelse(partial_rol_CIREN==partial_rol_NFL, 1, 0)
         ) %>%
  mutate(rol_match = 
           ifelse(ROL==rptpre_rol, 1, 0)
         ) %>%
  mutate(rptpre_nombre =
               tolower(rptpre_nombre)
               ) %>%
  mutate(NOM_PREDIO =
               tolower(NOM_PREDIO)
               ) %>%
  mutate(stringd =
           stringdist(NOM_PREDIO, rptpre_nombre, method = "dl")
         ) %>%
  mutate(under20 = 
           ifelse(stringd <=20, 1, 0))
  

```




``` {r join metrics, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE, eval = TRUE}

#  group by region

by_reg <- join_assess_df %>%
  group_by(rptpre_region)

summary_table <- by_reg %>% 
  summarise(
  number_of_projects = length(unique(rptpro_id)),
  number_of_stands = length(rptpro_id), 
  rol_match = mean(rol_match),
  similar_rol = mean(partial_rol_match),
  stringd = mean(stringd, na.rm = TRUE),
  under20 = mean(under20, na.rm = TRUE)
)

summary_table$geometry <- NULL

kable(summary_table, 
      "latex", 
      booktabs =T, 
      caption = "spatial join statistics"
      ) %>%
  kable_styling(latex_options = "hold_position", font_size = 6)

```




``` {r matching by rol, eval - FALSE}

#here, I just see how many rols match between the CIREN data and native forest law data

#projects_df is the native forest law projects 
#prop_rural.sf is the CIRN data with the rols as simple features object
rol_df <- df_stand %>%
  rename(ROL = rptpre_rol) %>% #renaming rols to be the same in both datasets
  inner_join(prop_rural.sf, by = "ROL") #merge by rol


# just creating a df to display only a couple of choice variables
rol_display <- rol_df %>%
  select(ROL, NOM_PREDIO, rptpre_nombre)
rol_display$geometry <- NULL

kable(rol_display[1:20,], 
      "latex", 
      booktabs =T, 
      caption = "merged on rol dataframe"
      ) %>%
  kable_styling(latex_options = "hold_position", font_size = 6)

length(unique(rol_df$ROL)) #find number of unique rol numbers found

```



