---
title: "preliminary stand analysis"
author: "Albert Garcia"
output:
  pdf_document:
    number_sections: yes
    toc: no
fontsize: 11pt    
documentclass: article
geometry: margin=1in
header-includes: 
  \usepackage{sectsty}
  \usepackage{enumitem}
  \usepackage{comment}
  \usepackage{multirow,array}
  \usepackage{makecell}
  \usepackage{dcolumn}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

### loads tidyverse packages, defines helper functions
library(latex2exp)
library(tinytex)
library(tidyverse)
library(ggplot2)
library(readxl)
library(sf)
library(stringi)
library(data.table)
library(kableExtra)
library(stringdist)
library(GADMTools)
library(rnaturalearth)
#library(reshape2)

library(did)
library(AER)
library(dynlm)
library(plm)
library(stargazer)
library(Metrics)
library(DataCombine)
library(Hmisc)

```




``` {r NFL_data, echo = FALSE, message = FALSE, warning = FALSE, include = FALSE, eval = TRUE}
#setting working directory

setwd("C:/Users/garci/Desktop/chile_data/nativeforestlaw")

# xls files downloaded from CONAF
#projects
proyecto_1 <- read_excel("proyectos_1.xls")
proyecto_2 <- read_excel("proyectos_2.xls")
proyecto_df <- merge(proyecto_1, proyecto_2, by = c("rptpro_id", "rptpro_numero_ingreso"), all=TRUE)
#properties and coordinates
predio_df <- read_excel("predio.xls")
coordinadas_predio_df <- read_excel("coordinadas_predio.xls")
#owners
propietario_df <- read_excel("propietario.xls")
#stands
rodal_1 <- read_excel("rodal_1.xls")
rodal_2 <- read_excel("rodal_2.xls")
rodal_df <- merge(rodal_1, rodal_2, by = c("rptro_id"), all=TRUE)
#activities
actividades_1 <- read_excel("actividades_1.xls")
actividades_2 <- read_excel("actividades_2.xls")
actividades_df <- merge(actividades_1, actividades_2, by = c("rptac_id"), all=TRUE)
#fences
cercos_df <- read_excel("cerco.xls")

#merging into full data set
df_NFL <- proyecto_df %>%
  left_join(predio_df, by = c("rptpro_id", "rptpro_numero_ingreso")) %>%
  left_join(propietario_df, by = "rptpre_id") %>%
  left_join(coordinadas_predio_df, by = "rptpre_id") %>%
  left_join(rodal_df, by = "rptpre_id") %>%
  left_join(actividades_df, by = "rptro_id")

property_df <- proyecto_df %>%
  left_join(predio_df, by = c("rptpro_id", "rptpro_numero_ingreso")) %>%
  left_join(propietario_df, by = "rptpre_id") %>%
  rename(ROL = rptpre_rol)
```


``` {r loading CIREN properties, echo = FALSE, message = FALSE, warning = FALSE, include = FALSE, eval = TRUE}

#uploading rural property cadastre shapefile

reg3.shp<- st_read("C:/Users/garci/Desktop/Roles_sad69_19s/III_REGION/rroles_3.shp")
reg4.shp<- st_read("C:/Users/garci/Desktop/Roles_sad69_19s/IV_REGION/region_4.shp")
reg11.shp<- st_read("C:/Users/garci/Desktop/Roles_sad69_19s/XI_REGION/region_11.shp")
reg12.shp<- st_read("C:/Users/garci/Desktop/Roles_sad69_19s/XII_REGION/PREDIOS-MARZO2007.shp")

# creating simple features object with shapefile
reg3.sf <- st_as_sf(reg3.shp) %>%
  st_set_crs("+proj=utm +zone=19 +south +ellps=aust_SA +units=m +no_defs") %>%
  st_transform("+proj=longlat +datum=WGS84") #transform crs
reg4.sf <- st_as_sf(reg4.shp) %>%
  st_set_crs("+proj=utm +zone=19 +south +ellps=aust_SA +units=m +no_defs") %>%
  st_transform("+proj=longlat +datum=WGS84") #transform crs
reg11.sf <- st_as_sf(reg11.shp) %>%
  st_set_crs("+proj=utm +zone=19 +south +ellps=aust_SA +units=m +no_defs") %>%
  st_transform("+proj=longlat +datum=WGS84") #transform crs
reg12.sf <- st_as_sf(reg12.shp) %>%
  st_set_crs("+proj=utm +zone=19 +south +ellps=aust_SA +units=m +no_defs") %>%
  st_transform("+proj=longlat +datum=WGS84") #transform crs

#uploading rural property cadastre shapefile
prop_rural.shp <- st_read(
  "C:/Users/garci/Desktop/chile_data/prop_rural/prop_rural.shp"
  )
# creating simple features object with rural properties shapefile
prop_rural.sf <- st_as_sf(prop_rural.shp) %>%
  st_transform("+proj=longlat +datum=WGS84")#transform crs
```

``` {r loading CIREN properties, echo = FALSE, message = FALSE, warning = FALSE, include = FALSE, eval = TRUE}
prop_rural.sf$dup_names <-
  (duplicated(prop_rural.sf$PROPIETARI) |
    duplicated(prop_rural.sf$PROPIETARI, fromLast=TRUE))*1

prop_dupowner <- prop_rural.sf %>%
  filter(dup_names == 1 & PROPIETARI != "NA") %>%
  left_join(property_df, by ="ROL") %>%
  group_by(ROL, rptpre_comuna) %>%
  mutate(first.treat = max(rptpro_ano))
```


