---
title: "land use and other covariates"
#author: "Albert Garcia"
output:
  pdf_document:
    number_sections: yes
    toc: no
fontsize: 11pt    
documentclass: article
geometry: margin=1in
header-includes: 
  \usepackage{sectsty}
  \usepackage{enumitem}
  \usepackage{comment}
  \usepackage{multirow,array}
  \usepackage{makecell}
  \usepackage{dcolumn}
---

```{r geoms, echo = FALSE, message = FALSE, warning = FALSE, include = FALSE, eval = TRUE}
############################################################################
## THE FILE PATHS IN THIS SCRIPT RELATE TO THE BREN CLUSTER ################
############################################################################

library(raster)
library(stars)
library(doParallel)
library(sp)
library(sf)
library(snow)
library(tidyverse)
library(tictoc)
library(data.table)
library(exactextractr)
library(nngeo)
library(rio)


lu2001_rast <- read_stars("input_data/lu_2001/lu_2001.tif")
st_crs(lu2001_rast)

roads.sf <- st_read(
  "input_data/CHL_rds/CHL_roads.shp"
  ) %>%
  st_transform(st_crs(lu2001_rast))%>%
  filter(RTT_DESCRI == "Primary Route" | RTT_DESCRI == "Secondary Route")

industry.sf <- st_read(
  "input_data/INDUSTRIA_FORESTAL/Catastro_Industria_Forestal_Primaria_Infor_2019.shp"
  ) %>%
  st_transform(st_crs(lu2001_rast))

`%notin%` <- Negate(`%in%`)
native_industry.sf <- industry.sf %>%
  filter(especies %notin% c("Eucalyptus delegatensis, Eucalyptus nitens", "Eucalyptus globulus", "Eucalyptus globulus, Eucalyptus nitens", "Pino radiata", "Eucalyptus nitens, Pino radiata", "Eucalyptus regnans" , "Eucalyptus globulus, Pino radiata", "Eucalyptus globulus, Eucalyptus nitens, Pino radiata", "Eucalyptus globulus, Eucalyptus Nitens, Pino radiata") )

erosion_actual.sf <- st_read(
  "input_data/erosion_actual.shp"
  ) %>%
  st_transform(st_crs(lu2001_rast))

riesgo_erosion.sf <- st_read(
  "input_data/riesgo_erosion_actual.shp"
  ) %>%
  st_transform(st_crs(lu2001_rast))

### start to get elevation and slope data
elevation <- getData('alt', country='CHL')[[1]]
terr <- terrain(elevation, opt=c('slope'), unit='degrees')


```


```{r mgmtplan}
# my_geoms.sf <- st_read(
#   "input_data/my_geoms/geoms.shp"
#   ) %>%
#   st_transform(st_crs(lu2001_rast))

my_geoms.sf <- st_read(
  "input_data/my_geoms/rol_match_geoms.shp"
  ) %>%
  st_transform(st_crs(lu2001_rast))

# my_geoms.sf <- st_read(
#   "input_data/my_geoms/spatial_match_geoms.shp"
#   ) %>%
#   st_transform(st_crs(lu2001_rast))


sf.object <- my_geoms.sf
stars.object <- lu2001_rast
rast <- as(stars.object, "Raster")
spatial.object <- as(sf.object, "Spatial")

num_cores <- 15

#--- number of polygons in a group ---#
num_in_group <- floor(nrow(sf.object)/num_cores)

#--- assign group id to polygons ---#
polys <- sf.object %>%  
  mutate(
    #--- create grid id ---#
    grid_id = 1:nrow(.),
    #--- assign group id  ---#
    group_id = grid_id %/% num_in_group + 1
  )


extract_by_group_reduced <- function(i){
  
  temp <- exact_extract(
    rast, 
    filter(polys, group_id == i)
  ) %>% 
    #--- combine the list of data.frames into one with polygon id ---#
    rbindlist(idcol = "id_within_group") %>% 
    group_by(id_within_group, value) %>%
    summarize(class_coverage = sum(coverage_fraction)) %>%
    group_by(id_within_group) %>%
    mutate(poly_total = sum(class_coverage),
           class_proportion = class_coverage/poly_total)
    
  temp_return <- as.data.frame(filter(polys, group_id == i))%>%
    mutate(id_within_group = (grid_id - min(grid_id) + 1)) %>%
    inner_join(temp, by = c("id_within_group"))
  
  return(temp_return)
}

tic()
#--- parallelized processing by group ---#
tempor <- mclapply(
  1:length(unique(polys$group_id)), 
  function(i) extract_by_group_reduced(i),
  mc.cores = num_cores
)    
toc()

class <- tempor %>%
  rbindlist(idcol = TRUE) 

class$value <- paste0("c_", class$value)

mgmt_class <- class %>%
  select(rptpro_id, value, class_proportion) %>%
  spread(key = "value", value = "class_proportion")%>%
  mutate_all(~replace(., is.na(.), 0))



sf.object <- sf.object %>%
  mutate(property_area_ha = as.numeric(units::set_units(st_area(.), ha)))

return_covs1 <- sf.object %>%
  mutate(road_dist = st_nn(., roads.sf, k = 1, returnDist = T, parallel = 15)[[2]],
         industry_dist = st_nn(., industry.sf, k = 1, returnDist = T, parallel = 15)[[2]],
         native_industry_dist = st_nn(., native_industry.sf, k = 1, returnDist = T, parallel = 15)[[2]],
         elev = unlist(exact_extract(elevation, ., 'mean')),
         slope = unlist(exact_extract(terr, ., 'mean'))
         )%>%
  st_centroid()

return_erosion <- sf.object %>%
  st_make_valid()%>%
  st_intersection(st_make_valid(erosion_actual.sf))%>%
  mutate(mod_to_severe_erosion_area = as.numeric(units::set_units(st_area(.), ha)))%>%  
  st_drop_geometry()%>%
  group_by(rptpro_id)%>%
  mutate(mod_to_severe_erosion_area = sum(mod_to_severe_erosion_area),
         mod_to_severe_erosion_area = ifelse(is.na(mod_to_severe_erosion_area), 0, mod_to_severe_erosion_area))%>%
  distinct(rptpro_id, .keep_all = TRUE)%>%
  dplyr::select(rptpro_id, mod_to_severe_erosion_area) # only select columns needed to merge


return_covs <- return_covs1 %>%
  mutate(lat = unlist(map(return_covs1$geometry,1)),
           long = unlist(map(return_covs1$geometry,2)))%>%
  left_join(mgmt_class, by = "rptpro_id")%>%
  left_join(return_erosion, by = "rptpro_id")%>%
  #left_join(return_erosionrisk, by = "prop_ID")%>%
  mutate(mod_to_severe_erosion_area = ifelse(is.na(mod_to_severe_erosion_area), 0, mod_to_severe_erosion_area), 
         proportion_erosion = mod_to_severe_erosion_area / property_area_ha
         #, proportion_erosion_risk = mod_to_severe_erosion_risk_area/property_area_ha)
  )
 
export(return_covs, "my_rol_match_covars.rds")
  
```




```{r rolarea}
# rolarea.sf <- st_read(
#   "rolarea_geoms.shp"
#   ) %>%
#   st_transform(st_crs(lu2001_rast))
# 
# sf.object <- rolarea.sf
# stars.object <- lu2001_rast
# rast <- as(stars.object, "Raster")
# spatial.object <- as(sf.object, "Spatial")
# 
# num_cores <- 15
# 
# #--- number of polygons in a group ---#
# num_in_group <- floor(nrow(sf.object)/num_cores)
# 
# #--- assign group id to polygons ---#
# polys <- sf.object %>%  
#   mutate(
#     #--- create grid id ---#
#     grid_id = 1:nrow(.),
#     #--- assign group id  ---#
#     group_id = grid_id %/% num_in_group + 1
#   )
# 
# 
# extract_by_group_reduced <- function(i){
#   
#   temp <- exact_extract(
#     rast, 
#     filter(polys, group_id == i)
#   ) %>% 
#     #--- combine the list of data.frames into one with polygon id ---#
#     rbindlist(idcol = "id_within_group") %>% 
#     group_by(id_within_group, value) %>%
#     summarize(class_coverage = sum(coverage_fraction)) %>%
#     group_by(id_within_group) %>%
#     mutate(poly_total = sum(class_coverage),
#            class_proportion = class_coverage/poly_total)
#     
#   temp_return <- as.data.frame(filter(polys, group_id == i))%>%
#     mutate(id_within_group = (grid_id - min(grid_id) + 1)) %>%
#     inner_join(temp, by = c("id_within_group"))
#   
#   return(temp_return)
# }
# 
# tic()
# #--- parallelized processing by group ---#
# tempor <- mclapply(
#   1:length(unique(polys$group_id)), 
#   function(i) extract_by_group_reduced(i),
#   mc.cores = num_cores
# )    
# toc()
# 
# class <- tempor %>%
#   rbindlist(idcol = TRUE) 
# 
# class$value <- paste0("c_", class$value)
# 
# rolarea_class <- class %>%
#   select(prop_ID, value, class_proportion) %>%
#   spread(key = "value", value = "class_proportion")%>%
#   mutate_all(~replace(., is.na(.), 0))
# 
# return_covs <- sf.object %>%
#   mutate(road_dist = st_nn(., roads.sf, k = 1, returnDist = T, parallel = 15)[[2]],
#          elev = unlist(exact_extract(elevation, ., 'mean')),
#          slope = unlist(exact_extract(terr, ., 'mean'))
#          #, area_ha = as.numeric(units::set_units(st_area(.), ha))
#          )%>%
#   st_centroid()
# 
# return_covs <- return_covs %>%
#   mutate(lat = unlist(map(return_covs$geometry,1)),
#            long = unlist(map(return_covs$geometry,2)))%>%
#   left_join(mgmt_class, by = "prop_ID")
# 
# export(return_covs, "rolarea_covars.rds")
#   
```

```{r}

losrios.sf <- st_read(
  "input_data/PROPIEDADES_RURALES/LOS_RÍOS_CIREN_2018.shp"
  ) %>%
  st_transform(st_crs(lu2001_rast))

sf.object <- losrios.sf

#--- number of polygons in a group ---#
num_in_group <- floor(nrow(sf.object)/num_cores)

#--- assign group id to polygons ---#
polys <- sf.object %>%  
  mutate(
    #--- create grid id ---#
    grid_id = 1:nrow(.),
    #--- assign group id  ---#
    group_id = grid_id %/% num_in_group + 1
  )

extract_by_group_reduced <- function(i){
  
  temp <- exact_extract(
    rast, 
    filter(polys, group_id == i)
  ) %>% 
    #--- combine the list of data.frames into one with polygon id ---#
    rbindlist(idcol = "id_within_group") %>% 
    group_by(id_within_group, value) %>%
    summarize(class_coverage = sum(coverage_fraction)) %>%
    group_by(id_within_group) %>%
    mutate(poly_total = sum(class_coverage),
           class_proportion = class_coverage/poly_total)
    
  temp_return <- as.data.frame(filter(polys, group_id == i))%>%
    mutate(id_within_group = (grid_id - min(grid_id) + 1)) %>%
    inner_join(temp, by = c("id_within_group"))
  
  return(temp_return)
}

tic()
#--- parallelized processing by group ---#
tempor <- mclapply(
  1:length(unique(polys$group_id)), 
  function(i) extract_by_group_reduced(i),
  mc.cores = num_cores
)    
toc()

class <- tempor %>%
  rbindlist(idcol = TRUE) 

class$value <- paste0("c_", class$value)

losrios_class <- class %>%
  select(objectid, rol, desccomu, value, class_proportion) %>%
  spread(key = "value", value = "class_proportion")%>%
  mutate_all(~replace(., is.na(.), 0))

########################################################################

sf.object <- sf.object %>%
  mutate(property_area_ha = as.numeric(units::set_units(st_area(.), ha)))

return_covs_losrios <- sf.object %>%
  mutate(road_dist = st_nn(., roads.sf, k = 1, returnDist = T, parallel = 15)[[2]],
         industry_dist = st_nn(., industry.sf, k = 1, returnDist = T, parallel = 15)[[2]],
         native_industry_dist = st_nn(., native_industry.sf, k = 1, returnDist = T, parallel = 15)[[2]],
         elev = unlist(exact_extract(elevation, ., 'mean')),
         slope = unlist(exact_extract(terr, ., 'mean'))
         )%>%
  st_centroid()

return_erosion <- sf.object %>%
  st_make_valid()%>%
  st_intersection(st_make_valid(erosion_actual.sf))%>%
  mutate(mod_to_severe_erosion_area = as.numeric(units::set_units(st_area(.), ha)))%>%  
  st_drop_geometry()%>%
  group_by(objectid, rol, desccomu)%>%
  mutate(mod_to_severe_erosion_area = ifelse(is.na(mod_to_severe_erosion_area), 0, mod_to_severe_erosion_area),
         mod_to_severe_erosion_area = sum(mod_to_severe_erosion_area))%>%
  distinct(objectid, rol, desccomu, .keep_all = TRUE)%>%
  dplyr::select(objectid, rol, desccomu, mod_to_severe_erosion_area) # only select columns needed to merge

return_covs_losrios <- return_covs_losrios %>%
  mutate(lat = unlist(map(return_covs_losrios$geometry,1)),
           long = unlist(map(return_covs_losrios$geometry,2)))%>%
  left_join(losrios_class, by = c("objectid", "rol", "desccomu"))%>%
  left_join(return_erosion, by = c("objectid", "rol", "desccomu"))%>%
  #left_join(return_erosionrisk, by = c("objectid", "rol", "desccomu"))%>%
  mutate(mod_to_severe_erosion_area = ifelse(is.na(mod_to_severe_erosion_area), 0, mod_to_severe_erosion_area), 
         proportion_erosion = mod_to_severe_erosion_area / property_area_ha
         #, proportion_erosion_risk = mod_to_severe_erosion_risk_area/property_area_ha)
  )
 
########################################################################


export(return_covs_losrios, "losrios_CIREN_covars.rds")



```

```{r}
# biobio and nuble
biobionuble.sf <- st_read(
  "input_data/PROPIEDADES_RURALES/BIOBÍO_CIREN_2016.shp"
  ) %>%
  st_transform(st_crs(lu2001_rast))

sf.object <- biobionuble.sf

#--- number of polygons in a group ---#
num_in_group <- floor(nrow(sf.object)/num_cores)

#--- assign group id to polygons ---#
polys <- sf.object %>%  
  mutate(
    #--- create grid id ---#
    grid_id = 1:nrow(.),
    #--- assign group id  ---#
    group_id = grid_id %/% num_in_group + 1
  )


tic()
#--- parallelized processing by group ---#
tempor <- mclapply(
  1:length(unique(polys$group_id)), 
  function(i) extract_by_group_reduced(i),
  mc.cores = num_cores
)    
toc()

class <- tempor %>%
  rbindlist(idcol = TRUE) 

class$value <- paste0("c_", class$value)

biobionuble_class <- class %>%
  select(objectid, rol, desccomu, value, class_proportion) %>%
  spread(key = "value", value = "class_proportion")%>%
  mutate_all(~replace(., is.na(.), 0))

########################################################################

sf.object <- sf.object %>%
  mutate(property_area_ha = as.numeric(units::set_units(st_area(.), ha)))

return_covs_biobionuble <- sf.object %>%
  mutate(road_dist = st_nn(., roads.sf, k = 1, returnDist = T, parallel = 15)[[2]],
         industry_dist = st_nn(., industry.sf, k = 1, returnDist = T, parallel = 15)[[2]],
         native_industry_dist = st_nn(., native_industry.sf, k = 1, returnDist = T, parallel = 15)[[2]],
         elev = unlist(exact_extract(elevation, ., 'mean')),
         slope = unlist(exact_extract(terr, ., 'mean'))
         )%>%
  st_centroid()

return_erosion <- sf.object %>%
  st_make_valid()%>%
  st_intersection(st_make_valid(erosion_actual.sf))%>%
  mutate(mod_to_severe_erosion_area = as.numeric(units::set_units(st_area(.), ha)))%>%  
  st_drop_geometry()%>%
  group_by(objectid, rol, desccomu)%>%
  mutate(mod_to_severe_erosion_area = ifelse(is.na(mod_to_severe_erosion_area), 0, mod_to_severe_erosion_area),
         mod_to_severe_erosion_area = sum(mod_to_severe_erosion_area))%>%
  distinct(objectid, rol, desccomu, .keep_all = TRUE)%>%
  dplyr::select(objectid, rol, desccomu, mod_to_severe_erosion_area) # only select columns needed to merge


return_covs_biobionuble <- return_covs_biobionuble %>%
  mutate(lat = unlist(map(return_covs_biobionuble$geometry,1)),
           long = unlist(map(return_covs_biobionuble$geometry,2)))%>%
  left_join(biobionuble_class, by = c("objectid", "rol", "desccomu"))%>%
  left_join(return_erosion, by = c("objectid", "rol", "desccomu"))%>%
  #left_join(return_erosionrisk, by = c("objectid", "rol", "desccomu"))%>%
  mutate(mod_to_severe_erosion_area = ifelse(is.na(mod_to_severe_erosion_area), 0, mod_to_severe_erosion_area), 
         proportion_erosion = mod_to_severe_erosion_area / property_area_ha
         #, proportion_erosion_risk = mod_to_severe_erosion_risk_area/property_area_ha)
  )
 
########################################################################

export(return_covs_biobionuble, "biobionuble_CIREN_covars.rds")



```

```{r maule}

maule.sf <- st_read(
  "input_data/PROPIEDADES_RURALES/MAULE_CIREN_2014.shp"
  ) %>%
  st_transform(st_crs(lu2001_rast))

sf.object <- maule.sf

#--- number of polygons in a group ---#
num_in_group <- floor(nrow(sf.object)/num_cores)

#--- assign group id to polygons ---#
polys <- sf.object %>%  
  mutate(
    #--- create grid id ---#
    grid_id = 1:nrow(.),
    #--- assign group id  ---#
    group_id = grid_id %/% num_in_group + 1
  )


tic()
#--- parallelized processing by group ---#
tempor <- mclapply(
  1:length(unique(polys$group_id)), 
  function(i) extract_by_group_reduced(i),
  mc.cores = num_cores
)    
toc()

class <- tempor %>%
  rbindlist(idcol = TRUE) 

class$value <- paste0("c_", class$value)

maule_class <- class %>%
  select(objectid, rol, desccomu, value, class_proportion) %>%
  spread(key = "value", value = "class_proportion")%>%
  mutate_all(~replace(., is.na(.), 0))

########################################################################

sf.object <- sf.object %>%
  mutate(property_area_ha = as.numeric(units::set_units(st_area(.), ha)))

return_covs_maule <- sf.object %>%
  mutate(road_dist = st_nn(., roads.sf, k = 1, returnDist = T, parallel = 15)[[2]],
         industry_dist = st_nn(., industry.sf, k = 1, returnDist = T, parallel = 15)[[2]],
         native_industry_dist = st_nn(., native_industry.sf, k = 1, returnDist = T, parallel = 15)[[2]],
         elev = unlist(exact_extract(elevation, ., 'mean')),
         slope = unlist(exact_extract(terr, ., 'mean'))
         )%>%
  st_centroid()

return_erosion <- sf.object %>%
  st_make_valid()%>%
  st_intersection(st_make_valid(erosion_actual.sf))%>%
  mutate(mod_to_severe_erosion_area = as.numeric(units::set_units(st_area(.), ha)))%>%  
  st_drop_geometry()%>%
  group_by(objectid, rol, desccomu)%>%
  mutate(mod_to_severe_erosion_area = ifelse(is.na(mod_to_severe_erosion_area), 0, mod_to_severe_erosion_area),
         mod_to_severe_erosion_area = sum(mod_to_severe_erosion_area))%>%
  distinct(objectid, rol, desccomu, .keep_all = TRUE)%>%
  dplyr::select(objectid, rol, desccomu, mod_to_severe_erosion_area) # only select columns needed to merge


return_covs_maule <- return_covs_maule %>%
  mutate(lat = unlist(map(return_covs_maule$geometry,1)),
           long = unlist(map(return_covs_maule$geometry,2)))%>%
  left_join(maule_class, by = c("objectid", "rol", "desccomu"))%>%
  left_join(return_erosion, by = c("objectid", "rol", "desccomu"))%>%
  #left_join(return_erosionrisk, by = c("objectid", "rol", "desccomu"))%>%
  mutate(mod_to_severe_erosion_area = ifelse(is.na(mod_to_severe_erosion_area), 0, mod_to_severe_erosion_area), 
         proportion_erosion = mod_to_severe_erosion_area / property_area_ha
         #, proportion_erosion_risk = mod_to_severe_erosion_risk_area/property_area_ha)
  )
 
########################################################################


export(return_covs_maule, "maule_CIREN_covars.rds")

```

```{r araucania}

araucania.sf <- st_read(
  "input_data/PROPIEDADES_RURALES/ARAUCANÍA_CIREN_2013.shp"
  ) %>%
  st_transform(st_crs(lu2001_rast))

sf.object <- araucania.sf

#--- number of polygons in a group ---#
num_in_group <- floor(nrow(sf.object)/num_cores)

#--- assign group id to polygons ---#
polys <- sf.object %>%  
  mutate(
    #--- create grid id ---#
    grid_id = 1:nrow(.),
    #--- assign group id  ---#
    group_id = grid_id %/% num_in_group + 1
  )


tic()
#--- parallelized processing by group ---#
tempor <- mclapply(
  1:length(unique(polys$group_id)), 
  function(i) extract_by_group_reduced(i),
  mc.cores = num_cores
)    
toc()

class <- tempor %>%
  rbindlist(idcol = TRUE) 

class$value <- paste0("c_", class$value)

araucania_class <- class %>%
  select(objectid, rol, desccomu, value, class_proportion) %>%
  spread(key = "value", value = "class_proportion")%>%
  mutate_all(~replace(., is.na(.), 0))

########################################################################

sf.object <- sf.object %>%
  mutate(property_area_ha = as.numeric(units::set_units(st_area(.), ha)))

return_covs_araucania <- sf.object %>%
  mutate(road_dist = st_nn(., roads.sf, k = 1, returnDist = T, parallel = 15)[[2]],
         industry_dist = st_nn(., industry.sf, k = 1, returnDist = T, parallel = 15)[[2]],
         native_industry_dist = st_nn(., native_industry.sf, k = 1, returnDist = T, parallel = 15)[[2]],
         elev = unlist(exact_extract(elevation, ., 'mean')),
         slope = unlist(exact_extract(terr, ., 'mean'))
         )%>%
  st_centroid()

return_erosion <- sf.object %>%
  st_make_valid()%>%
  st_intersection(st_make_valid(erosion_actual.sf))%>%
  mutate(mod_to_severe_erosion_area = as.numeric(units::set_units(st_area(.), ha)))%>%  
  st_drop_geometry()%>%
  group_by(objectid, rol, desccomu)%>%
  mutate(mod_to_severe_erosion_area = ifelse(is.na(mod_to_severe_erosion_area), 0, mod_to_severe_erosion_area),
         mod_to_severe_erosion_area = sum(mod_to_severe_erosion_area))%>%
  distinct(objectid, rol, desccomu, .keep_all = TRUE)%>%
  dplyr::select(objectid, rol, desccomu, mod_to_severe_erosion_area) # only select columns needed to merge

return_covs_araucania <- return_covs_araucania %>%
  mutate(lat = unlist(map(return_covs_araucania$geometry,1)),
           long = unlist(map(return_covs_araucania$geometry,2)))%>%
  left_join(araucania_class, by = c("objectid", "rol", "desccomu"))%>%
  left_join(return_erosion, by = c("objectid", "rol", "desccomu"))%>%
  #left_join(return_erosionrisk, by = c("objectid", "rol", "desccomu"))%>%
  mutate(mod_to_severe_erosion_area = ifelse(is.na(mod_to_severe_erosion_area), 0, mod_to_severe_erosion_area), 
         proportion_erosion = mod_to_severe_erosion_area / property_area_ha
         #, proportion_erosion_risk = mod_to_severe_erosion_risk_area/property_area_ha)
  )
 
########################################################################

export(return_covs_araucania, "araucania_CIREN_covars.rds")



```

```{r los lagos}

num_cores <- 15

loslagos.sf <- st_read(
  "input_data/PROPIEDADES_RURALES/LOS_LAGOS_CIREN_2016.shp"
  ) %>%
  st_transform(st_crs(lu2001_rast))



sf.object <- loslagos.sf

# stars.object <- lu2001_rast
rast <- as(stars.object, "Raster")
spatial.object <- as(sf.object, "Spatial")

#--- number of polygons in a group ---#
num_in_group <- floor(nrow(sf.object)/num_cores)

#--- assign group id to polygons ---#
polys <- sf.object %>%  
  mutate(
    #--- create grid id ---#
    grid_id = 1:nrow(.),
    #--- assign group id  ---#
    group_id = grid_id %/% num_in_group + 1
  )


tic()
#--- parallelized processing by group ---#
tempor <- mclapply(
  1:length(unique(polys$group_id)), 
  function(i) extract_by_group_reduced(i),
  mc.cores = num_cores
)    
toc()

class <- tempor %>%
  rbindlist(idcol = TRUE) 

class$value <- paste0("c_", class$value)

loslagos_class <- class %>%
  select(objectid, rol, desccomu, value, class_proportion) %>%
  spread(key = "value", value = "class_proportion")%>%
  mutate_all(~replace(., is.na(.), 0))


########################################################################

sf.object <- sf.object %>%
  mutate(property_area_ha = as.numeric(units::set_units(st_area(.), ha)))

return_covs_loslagos <- sf.object %>%
  mutate(road_dist = st_nn(., roads.sf, k = 1, returnDist = T, parallel = 15)[[2]],
         industry_dist = st_nn(., industry.sf, k = 1, returnDist = T, parallel = 15)[[2]],
         native_industry_dist = st_nn(., native_industry.sf, k = 1, returnDist = T, parallel = 15)[[2]],
         elev = unlist(exact_extract(elevation, ., 'mean')),
         slope = unlist(exact_extract(terr, ., 'mean'))
         )%>%
  st_centroid()

return_erosion <- sf.object %>%
  st_make_valid()%>%
  st_intersection(st_make_valid(erosion_actual.sf))%>%
  mutate(mod_to_severe_erosion_area = as.numeric(units::set_units(st_area(.), ha)))%>%  
  st_drop_geometry()%>%
  group_by(objectid, rol, desccomu)%>%
  mutate(mod_to_severe_erosion_area = ifelse(is.na(mod_to_severe_erosion_area), 0, mod_to_severe_erosion_area),
         mod_to_severe_erosion_area = sum(mod_to_severe_erosion_area))%>%
  distinct(objectid, rol, desccomu, .keep_all = TRUE)%>%
  dplyr::select(objectid, rol, desccomu, mod_to_severe_erosion_area) # only select columns needed to merge


return_covs_loslagos <- return_covs_loslagos %>%
  mutate(lat = unlist(map(return_covs_loslagos$geometry,1)),
           long = unlist(map(return_covs_loslagos$geometry,2)))%>%
  left_join(loslagos_class, by = c("objectid", "rol", "desccomu"))%>%
  left_join(return_erosion, by = c("objectid", "rol", "desccomu"))%>%
  #left_join(return_erosionrisk, by = c("objectid", "rol", "desccomu"))%>%
  mutate(mod_to_severe_erosion_area = ifelse(is.na(mod_to_severe_erosion_area), 0, mod_to_severe_erosion_area), 
         proportion_erosion = mod_to_severe_erosion_area / property_area_ha
         #, proportion_erosion_risk = mod_to_severe_erosion_risk_area/property_area_ha)
  )
 
########################################################################

export(return_covs_loslagos, "loslagos_CIREN_covars.rds")



```

```{r ohiggins}

ohiggins.sf <- st_read(
  "input_data/PROPIEDADES_RURALES/LIBERTADOR_GENERAL_BERNARDO_O_HIGGINS_CIREN_2013.shp"
  ) %>%
  st_transform(st_crs(lu2001_rast))

sf.object <- ohiggins.sf

stars.object <- lu2001_rast
rast <- as(stars.object, "Raster")
spatial.object <- as(sf.object, "Spatial")

#--- number of polygons in a group ---#
num_in_group <- floor(nrow(sf.object)/num_cores)

#--- assign group id to polygons ---#
polys <- sf.object %>%  
  mutate(
    #--- create grid id ---#
    grid_id = 1:nrow(.),
    #--- assign group id  ---#
    group_id = grid_id %/% num_in_group + 1
  )


tic()
#--- parallelized processing by group ---#
tempor <- mclapply(
  1:length(unique(polys$group_id)), 
  function(i) extract_by_group_reduced(i),
  mc.cores = num_cores
)    
toc()

class <- tempor %>%
  rbindlist(idcol = TRUE) 

class$value <- paste0("c_", class$value)

ohiggins_class <- class %>%
  select(objectid, rol, desccomu, value, class_proportion) %>%
  spread(key = "value", value = "class_proportion")%>%
  mutate_all(~replace(., is.na(.), 0))

########################################################################

sf.object <- sf.object %>%
  mutate(property_area_ha = as.numeric(units::set_units(st_area(.), ha)))

return_covs_ohiggins <- sf.object %>%
  mutate(road_dist = st_nn(., roads.sf, k = 1, returnDist = T, parallel = 15)[[2]],
         industry_dist = st_nn(., industry.sf, k = 1, returnDist = T, parallel = 15)[[2]],
         native_industry_dist = st_nn(., native_industry.sf, k = 1, returnDist = T, parallel = 15)[[2]],
         elev = unlist(exact_extract(elevation, ., 'mean')),
         slope = unlist(exact_extract(terr, ., 'mean'))
         )%>%
  st_centroid()

return_erosion <- sf.object %>%
  st_make_valid()%>%
  st_intersection(st_make_valid(erosion_actual.sf))%>%
  mutate(mod_to_severe_erosion_area = as.numeric(units::set_units(st_area(.), ha)))%>%  
  st_drop_geometry()%>%
  group_by(objectid, rol, desccomu)%>%
  mutate(mod_to_severe_erosion_area = ifelse(is.na(mod_to_severe_erosion_area), 0, mod_to_severe_erosion_area),
         mod_to_severe_erosion_area = sum(mod_to_severe_erosion_area))%>%
  distinct(objectid, rol, desccomu, .keep_all = TRUE)%>%
  dplyr::select(objectid, rol, desccomu, mod_to_severe_erosion_area) # only select columns needed to merge


return_covs_ohiggins <- return_covs_ohiggins %>%
  mutate(lat = unlist(map(return_covs_ohiggins$geometry,1)),
           long = unlist(map(return_covs_ohiggins$geometry,2)))%>%
  left_join(ohiggins_class, by = c("objectid", "rol", "desccomu"))%>%
  left_join(return_erosion, by = c("objectid", "rol", "desccomu"))%>%
  #left_join(return_erosionrisk, by = c("objectid", "rol", "desccomu"))%>%
  mutate(mod_to_severe_erosion_area = ifelse(is.na(mod_to_severe_erosion_area), 0, mod_to_severe_erosion_area), 
         proportion_erosion = mod_to_severe_erosion_area / property_area_ha
         #, proportion_erosion_risk = mod_to_severe_erosion_risk_area/property_area_ha)
  )
 
########################################################################

export(return_covs_ohiggins, "ohiggins_CIREN_covars.rds")



```

```{r aysen}

# aysen.sf <- st_read(
#   "input_data/PROPIEDADES_RURALES/AYSÉN_DEL_GENERAL_CARLOS_IBAÑEZ_DEL_CAMPO_CIREN_2004.shp"
#   ) %>%
#   st_transform(st_crs(lu2001_rast))
# 
# sf.object <- aysen.sf
# 
# stars.object <- lu2001_rast
# rast <- as(stars.object, "Raster")
# spatial.object <- as(sf.object, "Spatial")
# 
# #--- number of polygons in a group ---#
# num_in_group <- floor(nrow(sf.object)/num_cores)
# 
# #--- assign group id to polygons ---#
# polys <- sf.object %>%  
#   mutate(
#     #--- create grid id ---#
#     grid_id = 1:nrow(.),
#     #--- assign group id  ---#
#     group_id = grid_id %/% num_in_group + 1
#   )
# 
# 
# tic()
# #--- parallelized processing by group ---#
# tempor <- mclapply(
#   1:length(unique(polys$group_id)), 
#   function(i) extract_by_group_reduced(i),
#   mc.cores = num_cores
# )    
# toc()
# 
# class <- tempor %>%
#   rbindlist(idcol = TRUE) 
# 
# class$value <- paste0("c_", class$value)
# 
# aysen_class <- class %>%
#   select(objectid, rol, desccomu, value, class_proportion) %>%
#   spread(key = "value", value = "class_proportion")%>%
#   mutate_all(~replace(., is.na(.), 0))
# 
# return_covs_aysen <- sf.object %>%
#   mutate(road_dist = st_nn(., roads.sf, k = 1, returnDist = T, parallel = 20)[[2]],
#          elev = unlist(exact_extract(elevation, ., 'mean')),
#          slope = unlist(exact_extract(terr, ., 'mean')),
#          area_ha = as.numeric(units::set_units(st_area(.), ha)))%>%
#   st_centroid()%>%
#   mutate(lat = unlist(geometry)[1],
#          long = unlist(geometry)[2])%>%
#   left_join(aysen_class, by = c("objectid", "rol", "desccomu"))
# 
# export(return_covs_aysen, "aysen_CIREN_covars.rds")



```

```{r valparaiso}

valparaiso.sf <- st_read(
  "input_data/PROPIEDADES_RURALES/VALPARAÍSO_CIREN_2014.shp"
  ) %>%
  st_transform(st_crs(lu2001_rast))

sf.object <- valparaiso.sf

stars.object <- lu2001_rast
rast <- as(stars.object, "Raster")
spatial.object <- as(sf.object, "Spatial")

#--- number of polygons in a group ---#
num_in_group <- floor(nrow(sf.object)/num_cores)

#--- assign group id to polygons ---#
polys <- sf.object %>%  
  mutate(
    #--- create grid id ---#
    grid_id = 1:nrow(.),
    #--- assign group id  ---#
    group_id = grid_id %/% num_in_group + 1
  )


tic()
#--- parallelized processing by group ---#
tempor <- mclapply(
  1:length(unique(polys$group_id)), 
  function(i) extract_by_group_reduced(i),
  mc.cores = num_cores
)    
toc()

class <- tempor %>%
  rbindlist(idcol = TRUE) 

class$value <- paste0("c_", class$value)

valparaiso_class <- class %>%
  select(objectid, rol, desccomu, value, class_proportion) %>%
  spread(key = "value", value = "class_proportion")%>%
  mutate_all(~replace(., is.na(.), 0))

########################################################################

sf.object <- sf.object %>%
  mutate(property_area_ha = as.numeric(units::set_units(st_area(.), ha)))

return_covs_valparaiso <- sf.object %>%
  mutate(road_dist = st_nn(., roads.sf, k = 1, returnDist = T, parallel = 15)[[2]],
         industry_dist = st_nn(., industry.sf, k = 1, returnDist = T, parallel = 15)[[2]],
         native_industry_dist = st_nn(., native_industry.sf, k = 1, returnDist = T, parallel = 15)[[2]],
         elev = unlist(exact_extract(elevation, ., 'mean')),
         slope = unlist(exact_extract(terr, ., 'mean'))
         )%>%
  st_centroid()

return_erosion <- sf.object %>%
  st_make_valid()%>%
  st_intersection(st_make_valid(erosion_actual.sf))%>%
  mutate(mod_to_severe_erosion_area = as.numeric(units::set_units(st_area(.), ha)))%>%  
  st_drop_geometry()%>%
  group_by(objectid, rol, desccomu)%>%
  mutate(mod_to_severe_erosion_area = ifelse(is.na(mod_to_severe_erosion_area), 0, mod_to_severe_erosion_area),
         mod_to_severe_erosion_area = sum(mod_to_severe_erosion_area))%>%
  distinct(objectid, rol, desccomu, .keep_all = TRUE)%>%
  dplyr::select(objectid, rol, desccomu, mod_to_severe_erosion_area) # only select columns needed to merge


return_covs_valparaiso <- return_covs_valparaiso %>%
  mutate(lat = unlist(map(return_covs_valparaiso$geometry,1)),
           long = unlist(map(return_covs_valparaiso$geometry,2)))%>%
  left_join(valparaiso_class, by = c("objectid", "rol", "desccomu"))%>%
  left_join(return_erosion, by = c("objectid", "rol", "desccomu"))%>%
  #left_join(return_erosionrisk, by = c("objectid", "rol", "desccomu"))%>%
  mutate(mod_to_severe_erosion_area = ifelse(is.na(mod_to_severe_erosion_area), 0, mod_to_severe_erosion_area), 
         proportion_erosion = mod_to_severe_erosion_area / property_area_ha
         #, proportion_erosion_risk = mod_to_severe_erosion_risk_area/property_area_ha)
  )
 
########################################################################

export(return_covs_valparaiso, "valparaiso_CIREN_covars.rds")



```

```{r santiago}

santiago.sf <- st_read(
  "input_data/PROPIEDADES_RURALES/METROPOLITANA_CIREN_2015.shp"
  ) %>%
  st_transform(st_crs(lu2001_rast))

sf.object <- santiago.sf

stars.object <- lu2001_rast
rast <- as(stars.object, "Raster")
spatial.object <- as(sf.object, "Spatial")

#--- number of polygons in a group ---#
num_in_group <- floor(nrow(sf.object)/num_cores)

#--- assign group id to polygons ---#
polys <- sf.object %>%  
  mutate(
    #--- create grid id ---#
    grid_id = 1:nrow(.),
    #--- assign group id  ---#
    group_id = grid_id %/% num_in_group + 1
  )


tic()
#--- parallelized processing by group ---#
tempor <- mclapply(
  1:length(unique(polys$group_id)), 
  function(i) extract_by_group_reduced(i),
  mc.cores = num_cores
)    
toc()

class <- tempor %>%
  rbindlist(idcol = TRUE) 

class$value <- paste0("c_", class$value)

santiago_class <- class %>%
  select(objectid, rol, desccomu, value, class_proportion) %>%
  spread(key = "value", value = "class_proportion")%>%
  mutate_all(~replace(., is.na(.), 0))

########################################################################

sf.object <- sf.object %>%
  mutate(property_area_ha = as.numeric(units::set_units(st_area(.), ha)))

return_covs_santiago <- sf.object %>%
  mutate(road_dist = st_nn(., roads.sf, k = 1, returnDist = T, parallel = 15)[[2]],
         industry_dist = st_nn(., industry.sf, k = 1, returnDist = T, parallel = 15)[[2]],
         native_industry_dist = st_nn(., native_industry.sf, k = 1, returnDist = T, parallel = 15)[[2]],
         elev = unlist(exact_extract(elevation, ., 'mean')),
         slope = unlist(exact_extract(terr, ., 'mean'))
         )%>%
  st_centroid()

return_erosion <- sf.object %>%
  st_make_valid()%>%
  st_intersection(st_make_valid(erosion_actual.sf))%>%
  mutate(mod_to_severe_erosion_area = as.numeric(units::set_units(st_area(.), ha)))%>%  
  st_drop_geometry()%>%
  group_by(objectid, rol, desccomu)%>%
  mutate(mod_to_severe_erosion_area = ifelse(is.na(mod_to_severe_erosion_area), 0, mod_to_severe_erosion_area),
         mod_to_severe_erosion_area = sum(mod_to_severe_erosion_area))%>%
  distinct(objectid, rol, desccomu, .keep_all = TRUE)%>%
  dplyr::select(objectid, rol, desccomu, mod_to_severe_erosion_area) # only select columns needed to merge


return_covs_santiago <- return_covs_santiago %>%
  mutate(lat = unlist(map(return_covs_santiago$geometry,1)),
           long = unlist(map(return_covs_santiago$geometry,2)))%>%
  left_join(santiago_class, by = c("objectid", "rol", "desccomu"))%>%
  left_join(return_erosion, by = c("objectid", "rol", "desccomu"))%>%
  #left_join(return_erosionrisk, by = c("objectid", "rol", "desccomu"))%>%
  mutate(mod_to_severe_erosion_area = ifelse(is.na(mod_to_severe_erosion_area), 0, mod_to_severe_erosion_area), 
         proportion_erosion = mod_to_severe_erosion_area / property_area_ha
         #, proportion_erosion_risk = mod_to_severe_erosion_risk_area/property_area_ha)
  )
 
########################################################################
export(return_covs_santiago, "santiago_CIREN_covars.rds")



```

